### ISSUE TITLE
Categories show up as empty when collapsed

### ISSUE THREAD

**Issue by TheTabbingman** [nekomangaorg/Neko#1223]
### Steps to reproduce

1. Make Category
2. Add Manga to it
3. Collapse it

### Expected behavior

Should show the amount of manga in it even when collapsed

### Actual behavior

Says category is empty when collapsed

### Neko version

2.11.6

### Android version

Android 13

### Device

Google pixel 6

### Other details

![Screenshot_20221109-102730](https://user-images.githubusercontent.com/51281790/200888918-107f1300-40b7-48e2-bdab-c4f575b9807a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
I have yet been able to pin down why this happens, and doesn't happen on a fresh install 😞

**Comment by MrComexs** [comment]
This is also happening to me as well on my tablet but not my phone. I haven't been able to reproduce it with my phone.

Tablet:
Samsung Tab S7+
SM-T970
Neko: v2.13.3
Android 13
OneUI 5.1
764 dp

Phone:
Samsung Galaxy S10
SM-G973F
Neko: v2.13.3
Android 13
LineageOS: 20-20230526-Nightly-beyond1lte
411 dp

**Comment by CarlosEsco** [comment]
Same issue on 2.14.0?  It might be there until the eventual rewrite of the library screen.  Another option is backup, uninstall then reinstall app cause new installs don't have this issue.

**Comment by MrComexs** [comment]
I did still have this issue even after a reinstall but that was a month ago. but uninstalling and reinstalling to 2.14.0 did fix the bug.
