### ISSUE TITLE
Loading circle appearing in chapter

### ISSUE THREAD

**Issue by philippgaida** [nekomangaorg/Neko#1434]
### Steps to reproduce

1. Open any chapter
2. Leave Neko by changeing app, locking phone, etc.
3. Go back to Neko, chapter should still be open
4. Loading circle appears in the middle of the screen

### Expected behavior

Loading circle shouldn't appear

### Actual behavior

Loading circle appears.
Disappears when going back out of the chapter and opening it again or when changing the chapter (e.g. ch. 2 -> ch. 3)

### Neko version

2.13 - 2.16.3

### Android version

Android 12; Android 13

### Device

Fairphone 4

### Other details

Started happening after last update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by Resor12** [comment]
Bug still persists when switching between Neko and other apps in newest version

**Comment by nonproto** [comment]
@philippgaida let me know if this is still an issue for scenario 2
