### ISSUE TITLE
Going back from a manga detail screen to browse/display screen causes repeat network call

### ISSUE THREAD

**Issue by nonproto** [nekomangaorg/Neko#1570]
### Steps to reproduce

click browse, click seasonal, click a manga, click back.  Network call for the page is repeated

### Expected behavior

reduce network calls

### Actual behavior

no reduce

### Neko version

N/A

### Android version

N/A

### Device

N/A

### Other details

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by rajfp** [comment]
Currently postCreateView function of interface LifecycleListener used on Base controller is called again and again when we return to page which in turns calls onViewCreated which is extended by coroutine controller. Corresponding browse presenter loads home page on same callback function. I think there should be check if data has been loaded previously or not ,before hitting network call.
