### ISSUE TITLE
Failure to recognize manga titles

### ISSUE THREAD

**Issue by JosephShay** [nekomangaorg/Neko#1640]
### Steps to reproduce

![IMG_20240106_135604](https://github.com/nekomangaorg/Neko/assets/48162671/51e7173c-d3e4-42c3-a087-af012c5acb5b)
![IMG_20240106_135634](https://github.com/nekomangaorg/Neko/assets/48162671/9a453c4e-029c-4650-b480-c35586fa361d)
![IMG_20240106_135824](https://github.com/nekomangaorg/Neko/assets/48162671/1061f97e-44dd-485c-8c70-987f3ab6689d)

### Expected behavior

I expected the manga to normally go to another platform due to later problems and prevention with the last one.

### Actual behavior

Hello, great afternoon.
I don't know if this is the perfect place because tachiyomi support told me to come here, but I came here with a question about exporting the backup of the tachiyomi manga dex (normal)>neko

As seen in the three images, the pt-br option is active within the neko APK but the manga dex does not recognize the Br mangas of the manga dex itself.

### Neko version

2.14.2

### Android version

11

### Device

Realme 7i

### Other details

What exactly would be the problem? I sincerely apologize if it was poorly explained.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
I dunno why you are missing 2, but for Neko its 1 library entry.  When you enable other languages the chapters all show in that one entry.

So long story short the restore combined duplicates into 1 entry.

**Comment by JosephShay** [comment]
Well, from what I saw, the manga in the library were all in English only.

How could I resolve this?

**Comment by nonproto** [comment]
enable portuguese in the settings

**Comment by JosephShay** [comment]
As I showed in the post, I have already activated it previously

**Comment by nonproto** [comment]
refresh the library so it repulls the metadata

**Comment by JosephShay** [comment]
Could you specify the available options for the 'refresh' feature? I have come across several instances of this option within the application. In the event that the refresh option proves ineffective, what subsequent steps should I undertake? It's worth noting that I uninstalled the application some time ago and subsequently re-implemented certain procedures to investigate if any issues arose from my previous actions.

**Comment by nonproto** [comment]
go to a manga that you know has Portuguese chapters, swipe refresh in that page and it should update the manga and pull the missing chapters.
