### ISSUE TITLE
Apple IOS version

### ISSUE THREAD

**Issue by Dividedby0KSJ** [nekomangaorg/Neko#1641]
### Describe your suggested feature

The same app but for apple devices.

### Other details

I’m not saying to put it on the AppStore (because it probably won’t be approved.
Just a ipa file for side loading

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
No plans to add an IOS version, also it wouldn't be an easy task even if I did.
