### ISSUE TITLE
Browse page fails to load

### ISSUE THREAD

**Issue by eldonita** [nekomangaorg/Neko#1650]
### Steps to reproduce

By simply installing the app and going to the browse page 

### Expected behavior

Load the browse page correctly

### Actual behavior

infinite loading and then 
Unknown error 'failed to connect to api.mangadex.org'

### Neko version

2.14.2

### Android version

Android 14

### Device

Redmi Note 10 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Are you sure you are able to access mangadex?  That error is usually indicative of not being about to to connect due to ISP, router security or other
