### ISSUE TITLE
Add support for MDLists (CustomList)

### ISSUE THREAD

**Issue by D-Brox** [nekomangaorg/Neko#1654]
### Describe your suggested feature

Support for creating and viewing MDLists, and for adding/removing titles to the lists, similar to what's currently possible on the site:

![Screenshot_2024-01-22-21-59-47-619_tachiyomi mangadex-edit](https://github.com/nekomangaorg/Neko/assets/65723952/fa38f996-f186-452d-9608-b41a7a2958dc)

### Other details

[API reference](https://api.mangadex.org/docs/redoc.html#tag/CustomList) for the `CustomList` endpoints

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
This won't be implemented as this is the old MDList stuff.  I already have a full working local branch with the beta MdList changes, I am just waiting for MangaDex to go live in prod with that

**Comment by D-Brox** [comment]
Oh, I didn't know they were changing the API (the current one does look very inefficient tbh, so it makes sense they want to change it)

**Comment by D-Brox** [comment]
https://forums.mangadex.org/threads/follows-customlist-api-changelog-breaking-changes.1419832/

**Comment by nonproto** [comment]
That's not live in prod yet
