### ISSUE TITLE
Neko icon no longer offers Android Material You theme

### ISSUE THREAD

**Issue by LinkofHyrule89** [nekomangaorg/Neko#1665]
### Steps to reproduce

The updated icon looks great however, it doesn't appear to offer Android Material You themeing so it looks totally out of place on my home screen. 
![Screenshot_20240124-052045](https://github.com/nekomangaorg/Neko/assets/3983279/cfab50b9-3ed1-4b90-b982-b6a82cc1843d)

### Expected behavior

The new icon should support Android Material You themeing.

### Actual behavior

The icon ignores the system theme and looks out of place.

### Neko version

2.15.0

### Android version

Android 14

### Device

Google Pixel 4a 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
good point, I knew I was forgetting something.  I'll add it to my todo for the next release

**Comment by LinkofHyrule89** [comment]
Awesome thanks for the quick reply!

**Comment by LinkofHyrule89** [comment]
This still doesn't seem to be in the new update did it get merged in?

**Comment by nonproto** [comment]
Seems to have been in the debug folder so. The debug icon was theming. I will fix it for the next release coming today

**Comment by LinkofHyrule89** [comment]
It's working now thanks a lot!
