### ISSUE TITLE
Question Marks diamond in between stuff

### ISSUE THREAD

**Issue by TheTabbingman** [nekomangaorg/Neko#1671]
### Steps to reproduce

Open manga details page.

### Expected behavior

No question mark diamond should appear.

### Actual behavior

Question mark diamond appears between authors and artists, and between date and group.

### Neko version

2.15.0

### Android version

Android 14

### Device

Google pixel 6

### Other details

![Screenshot_20240124-212512](https://github.com/nekomangaorg/Neko/assets/51281790/a35b5d26-1559-4b4d-b660-0b441dc5238a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
damn the kotlin formatter changed that

**Comment by nonproto** [comment]
have to do a hto fix release but if you experience this issue still redownload 2.16.0
