### ISSUE TITLE
neko skips all updates "because at least one tracker has status of Unfollowed"

### ISSUE THREAD

**Issue by m4rch3n1ng** [nekomangaorg/Neko#1674]
### Steps to reproduce

update library

### Expected behavior

it should update the library

(or tell me which trackers have status of Unfollowed)

### Actual behavior

it skips updating all 174 entries in my library

the neko update log shows the error `! Skipped because at least one tracker has status of Unfollowed`

not sure what that means but i checked and as far as i can tell none of the entries in my library have the tracker status of unfollowed

also everything worked before the latest update

### Neko version

2.15.0

### Android version

android 11

### Device

samsung galaxy 050

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by m4rch3n1ng** [comment]
i found a workaround by disabling smart library update restrictions, but i don't get why it seems to think every single manga has a tracking status of "Unfollowed", even though i have them as "Reading"

![image](https://github.com/nekomangaorg/Neko/assets/63159454/fb85054e-4f9e-4428-b285-aa8a119d4610)
![image](https://github.com/nekomangaorg/Neko/assets/63159454/cee9ae76-8a84-4317-874a-d3549aba3bb3)

**Comment by nonproto** [comment]
> i found a workaround by disabling smart library update restrictions, but i don't get why it seems to think every single manga has a tracking status of "Unfollowed", even though i have them as "Reading"
> 
> ![image](https://github.com/nekomangaorg/Neko/assets/63159454/fb85054e-4f9e-4428-b285-aa8a119d4610)
> ![image](https://github.com/nekomangaorg/Neko/assets/63159454/00a40469-c912-4ac5-acd0-761c9931b76b)
> 
> 

What other trackers are on that manga?

**Comment by nonproto** [comment]
unfollowed is definitely, bugged.  I will fix it for next release.

**Comment by m4rch3n1ng** [comment]
> What other trackers are on that manga?

i don't think there are any other trackers? how do i check that?

![image](https://github.com/nekomangaorg/Neko/assets/63159454/372e3eee-2bd5-4319-9eae-4909fa37987b)
![image](https://github.com/nekomangaorg/Neko/assets/63159454/8dc4f4bb-3ead-4f7f-a2f1-b49641994d47)

**Comment by nonproto** [comment]
no worries that one is definitely bugged

**Comment by CaidenBlock** [comment]
Did some testing and this applies for all statuses, not just unfollowed, also Completed and Plan to Read seem to be mutually inclusive with no user feedback, I can't seem to just select one of them.

https://github.com/nekomangaorg/Neko/assets/34176510/3429b496-818a-4853-8047-725db0f0e1ea

**Comment by nonproto** [comment]
> Did some testing and this applies for all statuses, not just unfollowed.

No worries I already fixed it for next release. The Boolean check was opposite

**Comment by CaidenBlock** [comment]
> > Did some testing and this applies for all statuses, not just unfollowed.
> 
> No worries I already fixed it for next release. The Boolean check was opposite

ah, my cli didn't show the staged tag
