### ISSUE TITLE
Neko is not fully updating your favorite mangas

### ISSUE THREAD

**Issue by Chibi8357** [nekomangaorg/Neko#1675]
### Steps to reproduce

1. Go to recent tab
2. Slide down so Neko can update mangas in favorite list and fetch new chapters
3. Neko only update a few select mangas and skips everything else

### Expected behavior

Neko updates all favorite manga and fetch new chapters 

### Actual behavior

Neko updates only a few mangas and skips all the other mangas

### Neko version

2.15.0

### Android version

Android 13

### Device

Samsung s20+

### Other details

https://youtu.be/fQ_s0GMGWkU?si=6zw22cAQpBkNgouV
I made a short unlisted youtube video so it would be easier to understand the problem [](https://youtu.be/fQ_s0GMGWkU?si=6zw22cAQpBkNgouV)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by babyblasphemy** [comment]
Click the drop down on the notification saying the manga were skipped to see why they were skipped. Is it because they had tracker status of unfollowed?
If so, navigate to Settings>Library>Smart library update restrictions and deselect BOTH Tracking status Planned to Read AND Completed.

**Comment by Chibi8357** [comment]
Thank you for your reply, that fixed the problem

**Comment by nonproto** [comment]
> Click the drop down on the notification saying the manga were skipped to see why they were skipped. Is it because they had tracker status of unfollowed?
> If so, navigate to Settings>Library>Smart library update restrictions and deselect BOTH Tracking status Planned to Read AND Completed. 

How would unchecking Planned to read and completed fix unfollowed?

**Comment by nonproto** [comment]
This change was mentioned in the change log.
