### ISSUE TITLE
Skipped all updates because "series is complete"

### ISSUE THREAD

**Issue by Milan8890** [nekomangaorg/Neko#1680]
### Steps to reproduce

I just update my library as usual but it skips all with a log that looks if all of them were completed.

### Expected behavior

Skip only the actually completed ones

### Actual behavior

Skips instead everything

### Neko version

2.15.0

### Android version

13

### Device

Redmi note 12 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
This is fixed in next release
