### ISSUE TITLE
Api issues on the MyAnimeList tracker

### ISSUE THREAD

**Issue by D-Brox** [nekomangaorg/Neko#1682]
### Steps to reproduce

1. Login with the MAL tracker
2. Try syncing any title

### Expected behavior

No issues syncing titles or chapter read status

### Actual behavior

Http errors 403 and 503 when finishing reading a chapter or trying to sync a title:

![1706826811282](https://github.com/nekomangaorg/Neko/assets/65723952/9ab76ec2-8fb1-416f-98e7-7d6c6caff1af)

![1706826811288](https://github.com/nekomangaorg/Neko/assets/65723952/948d9416-cae5-40eb-829a-c433694adf3e)

### Neko version

2.15.0

### Android version

Android 13

### Device

Xiaomi Poco X4 Pro

### Other details

MAL recently experienced API issues, and this issue is probably the result of their countermeasures.

This also has already been dealt with in https://github.com/mihonapp/mihon/commit/0f4de03d7a77b52490dc9a95e96a308b93b26e4f , which I believe I could port here.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
2.16.0
