### ISSUE TITLE
Neko 2.16.0 is a new install

### ISSUE THREAD

**Issue by nonproto** [nekomangaorg/Neko#1684]
The new version of Neko (when released).  Will be a completely new install.  The older versions will still work with whatever bugs it has.  It will just prompt you to update to 2.16.0 every time.  Once you install 2.16.0,   Make a backup of your library and place in a safe location, then uninstall 2.15.0.

If you have downloads and are confused what to do refer to the mihon guide about migrating.  
https://mihon.app/docs/faq/storage#migrating-from-tachiyomi-v0-14-x-or-earlier

after you copy your downloads, you will need to run `Settings -> Advanced Settings -> Refresh the download cache`

**Comment by Efreak** [comment]
Is there a reason why the package ID changed?

**Comment by nonproto** [comment]
> Is there a reason why the package ID changed?

I wanted the package id to actually match the app.  The previous one was before Neko had a name and was `tachiyomi.mangadex`

**Comment by escalonn** [comment]
ugh, this seemingly pointless update caused me to lose all my carefully evaluated settings since i was allowed to assume the library backup would contain that kind of thing

**Comment by nonproto** [comment]
> ugh, this seemingly pointless update caused me to lose all my carefully evaluated settings since i was allowed to assume the library backup would contain that kind of thing

It takes less then 2 mins to adjust settings. If that's too much of a hassle you can use a different app
