### ISSUE TITLE
Library Smart Update settings causes crash

### ISSUE THREAD

**Issue by hullmat998** [nekomangaorg/Neko#1691]
### Steps to reproduce

1) Open App
2) go to settings
3) go to library settings and click Smart Update settings. 
4) see dump log and option to restart app

### Expected behavior

The expect behavior would be for the settings to open up so the filters can be turned off.

### Actual behavior

The app crashes. 

### Crash logs

App version: 2.16.0 (standard, 4107d3dba, 1, 2024-02-06T19:13:30.594121294)
Android version: 14 (SDK 34)
Android build ID: UQ1A.240105.004
Device brand: google
Device manufacturer: Google
Device name: husky
Device model: Pixel 8 Pro
Device product name: husky
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
at android.widget.AbsListView.obtainView(AbsListView.java:2466)
at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
at android.widget.ListView.onMeasure(ListView.java:1321)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
at android.view.View.measure(View.java:27133)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of crash
02-06 15:05:51.019  8524  8524 E AndroidRuntime: FATAL EXCEPTION: main
02-06 15:05:51.019  8524  8524 E AndroidRuntime: Process: org.nekomanga.neko, PID: 8524
02-06 15:05:51.019  8524  8524 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2466)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1321)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:882)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-06 15:05:51.019  8524  8524 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
--------- beginning of main
02-06 15:12:01.221 16125 16860 D vulkan  : searching for layers in '/data/app/~~htkji_CEehyuJcwplbp-tg==/org.nekomanga.neko-wh1_u6Fkhz2XlBMMrBkyIA==/lib/arm64'
02-06 15:12:01.222 16125 16860 D vulkan  : searching for layers in '/data/app/~~htkji_CEehyuJcwplbp-tg==/org.nekomanga.neko-wh1_u6Fkhz2XlBMMrBkyIA==/base.apk!/lib/arm64-v8a'
02-06 15:12:01.225 16125 16125 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
02-06 15:12:01.246 16125 16125 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10238; state: ENABLED
02-06 15:12:01.270 16125 16125 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10238; state: ENABLED
02-06 15:12:01.299 16125 16177 E SQLiteLog: (284) automatic index on C(manga_id)
02-06 15:12:01.299 16125 16177 E SQLiteLog: (284) automatic index on R(manga_id)
02-06 15:12:01.299 16125 16177 E SQLiteLog: (284) automatic index on B(manga_id)
02-06 15:12:01.299 16125 16177 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-06 15:12:01.320 16125 16158 D SessionLifecycleClient: Sending lifecycle 1 to service
02-06 15:12:01.321 16125 16180 D SessionLifecycleService: Activity foregrounding at 420662.
02-06 15:12:01.321 16125 16180 D SessionLifecycleService: Cold start detected.
02-06 15:12:01.321 16125 16878 I FA      : Tag Manager is not found and thus will not be used
02-06 15:12:01.322 16125 16180 D SessionLifecycleService: Generated new session f0f479e65605430a86d2faf1dbba07dc
02-06 15:12:01.322 16125 16180 D SessionLifecycleService: Broadcasting new session: SessionDetails(sessionId=f0f479e65605430a86d2faf1dbba07dc, firstSessionId=f0f479e65605430a86d2faf1dbba07dc, sessionIndex=0, sessionStartTimestampUs=1707250321322000)
02-06 15:12:01.322 16125 16158 D SessionFirelogPublisher: Data Collection is enabled for at least one Subscriber
02-06 15:12:01.323 16125 16125 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10238; state: DISABLED
02-06 15:12:01.324 16125 16147 D EventGDTLogger: Session Event: {"eventType":1,"sessionData":{"sessionId":"f0f479e65605430a86d2faf1dbba07dc","firstSessionId":"f0f479e65605430a86d2faf1dbba07dc","sessionIndex":0,"eventTimestampUs":1707250321322000,"dataCollectionStatus":{"performance":1,"crashlytics":2,"sessionSamplingRate":1.0},"firebaseInstallationId":"cIomwkysSpiuLdG8rjNZjn"},"applicationInfo":{"appId":"1:458852344739:android:e0349329975aef7eb37016","deviceModel":"Pixel 8 Pro","sessionSdkVersion":"1.2.1","osVersion":"14","logEnvironment":3,"androidAppInfo":{"packageName":"org.nekomanga.neko","versionName":"2.16.0","appBuildVersion":"1","deviceManufacturer":"Google","currentProcessDetails":{"processName":"org.nekomanga.neko","pid":16125,"importance":100,"defaultProcess":true},"appProcessDetails":[{"processName":"org.nekomanga.neko","pid":16125,"importance":100,"defaultProcess":true}]}}}
02-06 15:12:01.324 16125 16147 D SessionFirelogPublisher: Successfully logged Session Start event: f0f479e65605430a86d2faf1dbba07dc
02-06 15:12:01.369 16125 16125 D SessionLifecycleClient: Session update received: f0f479e65605430a86d2faf1dbba07dc
02-06 15:12:01.371 16125 16158 D SessionLifecycleClient: Notified CRASHLYTICS of new session f0f479e65605430a86d2faf1dbba07dc
02-06 15:12:03.687 16125 16928 D TrafficStats: tagSocket(169) with statsTag=0xffffffff, statsUid=-1
02-06 15:12:03.687 16125 16927 D TrafficStats: tagSocket(155) with statsTag=0xffffffff, statsUid=-1
02-06 15:12:03.688 16125 16926 D TrafficStats: tagSocket(147) with statsTag=0xffffffff, statsUid=-1
02-06 15:12:03.689 16125 16930 D TrafficStats: tagSocket(157) with statsTag=0xffffffff, statsUid=-1
02-06 15:12:03.690 16125 16929 D TrafficStats: tagSocket(158) with statsTag=0xffffffff, statsUid=-1
02-06 15:12:04.610 16125 16135 W System  : A resource failed to call close. 
02-06 15:12:06.207 16125 16125 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Dialog$$ExternalSyntheticLambda2@de84b34
02-06 15:12:06.209 16125 16860 D OpenGLRenderer: endAllActiveAnimators on 0xb40000780812dcc0 (RippleDrawable) with handle 0xb4000079d7cedd80
02-06 15:12:10.835 16125 16125 D AndroidRuntime: Shutting down VM
02-06 15:12:10.836 16125 16125 E AndroidRuntime: FATAL EXCEPTION: main
02-06 15:12:10.836 16125 16125 E AndroidRuntime: Process: org.nekomanga.neko, PID: 16125
02-06 15:12:10.836 16125 16125 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2466)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1321)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:882)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-06 15:12:10.836 16125 16125 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
02-06 15:12:10.838 16125 16145 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10238; state: ENABLED
02-06 15:12:10.859 16125 16125 I .nekomanga.neko: System.exit called, status: 0
02-06 15:12:10.859 16125 16125 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
02-06 15:12:10.911 16945 16945 I o:error_handler: Using CollectorTypeCC GC.
02-06 15:12:10.913 16945 16945 E o:error_handler: Not starting debugger since process cannot load the jdwp agent.
02-06 15:12:10.920 16945 16945 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10238; state: ENABLED
02-06 15:12:10.920 16945 16945 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10238; state: ENABLED
02-06 15:12:10.922 16945 16945 D ApplicationLoaders: Returning zygote-cached class loader: /system_ext/framework/androidx.window.extensions.jar
02-06 15:12:10.922 16945 16945 D ApplicationLoaders: Returning zygote-cached class loader: /system_ext/framework/androidx.window.sidecar.jar
02-06 15:12:10.932 16945 16945 D nativeloader: Configuring clns-6 for other apk /data/app/~~htkji_CEehyuJcwplbp-tg==/org.nekomanga.neko-wh1_u6Fkhz2XlBMMrBkyIA==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~htkji_CEehyuJcwplbp-tg==/org.nekomanga.neko-wh1_u6Fkhz2XlBMMrBkyIA==/lib/arm64:/data/app/~~htkji_CEehyuJcwplbp-tg==/org.nekomanga.neko-wh1_u6Fkhz2XlBMMrBkyIA==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/org.nekomanga.neko
02-06 15:12:10.940 16945 16945 I MultiDex: VM with version 2.1.0 has multidex support
02-06 15:12:10.940 16945 16945 I MultiDex: Installing application
02-06 15:12:10.940 16945 16945 I MultiDex: VM has multidex support, MultiDex support library is disabled.
02-06 15:12:10.942 16945 16945 W ziparchive: Unable to open '/data/app/~~y2Ma1RTz_7fa8Mcc3LnuSw==/com.google.android.trichromelibrary_609923033-xq02jlHz-sWeL9lGRDCETQ==/base.dm': No such file or directory
02-06 15:12:10.942 16945 16945 W ziparchive: Unable to open '/data/app/~~y2Ma1RTz_7fa8Mcc3LnuSw==/com.google.android.trichromelibrary_609923033-xq02jlHz-sWeL9lGRDCETQ==/base.dm': No such file or directory
02-06 15:12:10.942 16945 16945 W o:error_handler: Entry not found
02-06 15:12:10.943 16945 16945 D nativeloader: Configuring clns-7 for other apk /data/app/~~y2Ma1RTz_7fa8Mcc3LnuSw==/com.google.android.trichromelibrary_609923033-xq02jlHz-sWeL9lGRDCETQ==/base.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/data/app/~~ueY7RLcwq4HhjPd0lJCqMQ==/com.google.android.webview-eVy2b1X-5ojS4EJievVRbg==/lib/arm64:/data/app/~~ueY7RLcwq4HhjPd0lJCqMQ==/com.google.android.webview-eVy2b1X-5ojS4EJievVRbg==/base.apk!/lib/arm64-v8a:/data/app/~~y2Ma1RTz_7fa8Mcc3LnuSw==/com.google.android.trichromelibrary_609923033-xq02jlHz-sWeL9lGRDCETQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
02-06 15:12:10.943 16945 16945 D nativeloader: Extending system_exposed_libraries: libedgetpu_dba.google.so
02-06 15:12:10.943 16945 16945 D nativeloader: Configuring clns-8 for other apk /data/app/~~ueY7RLcwq4HhjPd0lJCqMQ==/com.google.android.webview-eVy2b1X-5ojS4EJievVRbg==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~ueY7RLcwq4HhjPd0lJCqMQ==/com.google.android.webview-eVy2b1X-5ojS4EJievVRbg==/lib/arm64:/data/app/~~ueY7RLcwq4HhjPd0lJCqMQ==/com.google.android.webview-eVy2b1X-5ojS4EJievVRbg==/base.apk!/lib/arm64-v8a:/data/app/~~y2Ma1RTz_7fa8Mcc3LnuSw==/com.google.android.trichromelibrary_609923033-xq02jlHz-sWeL9lGRDCETQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand
02-06 15:12:10.944 16945 16945 I WebViewFactory: Loading com.google.android.webview version 120.0.6099.230 (code 609923033)
02-06 15:12:10.953 16945 16945 I cr_WVCFactoryProvider: Loaded version=120.0.6099.230 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
02-06 15:12:10.956 16945 16966 E chromium: [0206/151210.956803:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
02-06 15:12:10.960 16945 16945 I cr_LibraryLoader: Successfully loaded native library
02-06 15:12:10.960 16945 16945 I cr_CachingUmaRecorder: Flushed 7 samples from 7 histograms, 0 samples were dropped.
02-06 15:12:10.992 16945 16945 W Iconics : At least one font needs to be registered first
02-06 15:12:10.992 16945 16945 W Iconics :     via com.mikepenz.iconics.Iconics.registerFont(Iconics.kt:117)
02-06 15:12:11.008 16945 16984 D vulkan  : searching for layers in '/data/app/~~htkji_CEehyuJcwplbp-tg==/org.nekomanga.neko-wh1_u6Fkhz2XlBMMrBkyIA==/lib/arm64'
02-06 15:12:11.008 16945 16984 D vulkan  : searching for layers in '/data/app/~~htkji_CEehyuJcwplbp-tg==/org.nekomanga.neko-wh1_u6Fkhz2XlBMMrBkyIA==/base.apk!/lib/arm64-v8a'
02-06 15:12:11.012 16945 16945 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
02-06 15:12:11.033 16945 16945 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10238; state: DISABLED
02-06 15:12:11.066 16945 16945 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10238; state: ENABLED
02-06 15:12:14.964 17009 17009 W logcat  : type=1400 audit(0.0:113): avc:  denied  { ioctl } for  path="/storage/emulated/0/Android/data/org.nekomanga.neko/cache/neko_crash_logs.txt" dev="fuse" ino=0 ioctlcmd=0xf50d scontext=u:r:untrusted_app:s0:c238,c256,c512,c768 tcontext=u:object_r:fuse:s0 tclass=file permissive=0 app=org.nekomanga.neko

### Neko version

2.16.0

### Android version

Android 14

### Device

Google Pixel 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by lordmage** [comment]
Same when going to smart update restrictions app crashed with dump and restart as only [dump log](https://drive.google.com/file/d/1dmDBqDxFwffz2UDNUxMyX9clMsFBCkS1/view?usp=drivesdk)

**Comment by Norsze** [comment]
Same crash on Galaxy s22+ android 14

[neko_crash_logs.txt](https://github.com/nekomangaorg/Neko/files/14186346/neko_crash_logs.txt)

**Comment by nonproto** [comment]
I'll release 2.16.1 soonish
