### ISSUE TITLE
Store files in `/Android/data/org.nekomanga.neko`

### ISSUE THREAD

**Issue by NatoBoram** [nekomangaorg/Neko#1692]
### Describe your suggested feature

`v2.16.0` is currently forcing the selection of a user-visible folder inside `/sdcard`. However, I don't particularly want to access this data. I want to hide it in the app's public storage.

There should be an option to *not* select a folder and let Neko use its dedicated `/Android/data/org.nekomanga.neko` folder.

![Screenshot_20240206-155802](https://github.com/nekomangaorg/Neko/assets/10495562/6037f43e-c741-4bbd-b286-a666bb6c56a0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
I have no plans to allow selecting The app directory. Everything in this folder, including downloads, save pages and save covers should be accessible
