### ISSUE TITLE
Crash when trying to edit Smart Library Update Restrictions

### ISSUE THREAD

**Issue by deusexcalamus** [nekomangaorg/Neko#1696]
### Steps to reproduce

Open neko
go to settings>library>tap smart library update restrictions
crash

### Expected behavior

I should be able to edit these restrictions.

### Actual behavior

The app crashes.

### Crash logs

App version: 2.16.0 (standard, 4107d3dba, 1, 2024-02-06T19:13:30.594121294)
Android version: 14 (SDK 34)
Android build ID: UQ1A.240105.002
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
at android.widget.AbsListView.obtainView(AbsListView.java:2466)
at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
at android.widget.ListView.onMeasure(ListView.java:1321)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27133)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
at android.view.View.measure(View.java:27133)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8248)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of crash
02-06 17:07:01.895 14433 14433 E AndroidRuntime: FATAL EXCEPTION: main
02-06 17:07:01.895 14433 14433 E AndroidRuntime: Process: org.nekomanga.neko, PID: 14433
02-06 17:07:01.895 14433 14433 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2466)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1321)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:882)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-06 17:07:01.895 14433 14433 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: FATAL EXCEPTION: main
02-06 17:07:16.660 15346 15346 E AndroidRuntime: Process: org.nekomanga.neko, PID: 15346
02-06 17:07:16.660 15346 15346 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2466)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1321)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:882)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-06 17:07:16.660 15346 15346 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
--------- beginning of main
02-06 17:08:29.354 15519 15519 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Dialog$$ExternalSyntheticLambda2@4b868dc
02-06 17:08:29.357 15519 15628 D OpenGLRenderer: endAllActiveAnimators on 0xb4000076687acd50 (RippleDrawable) with handle 0xb400007598379de0
02-06 17:11:22.328 15519 15566 D SessionLifecycleClient: Sending lifecycle 2 to service
02-06 17:11:22.328 15519 15598 D SessionLifecycleService: Activity backgrounding at 285530276
02-06 17:11:22.332 15519 15589 E SQLiteLog: (284) automatic index on mangas(_id)
02-06 17:11:22.855 15519 15528 W .nekomanga.neko: Cleared Reference was only reachable from finalizer (only reported once)
02-06 17:11:22.937 15519 15528 I .nekomanga.neko: NativeAlloc concurrent mark compact GC freed 225006(10MB) AllocSpace objects, 81(3328KB) LOS objects, 75% free, 15MB/60MB, paused 1.224ms,16.458ms total 220.800ms
02-06 17:11:24.361 15519 15801 I FA      : Application backgrounded at: timestamp_millis: 1707261082358
02-06 17:11:24.732 15519 15528 I .nekomanga.neko: NativeAlloc concurrent mark compact GC freed 45788(2270KB) AllocSpace objects, 22(792KB) LOS objects, 75% free, 13MB/54MB, paused 1.470ms,7.981ms total 199.373ms
02-06 17:11:26.246 15519 15528 I .nekomanga.neko: NativeAlloc concurrent mark compact GC freed 6351(496KB) AllocSpace objects, 29(1588KB) LOS objects, 75% free, 13MB/53MB, paused 715us,8.607ms total 153.381ms
02-06 17:15:28.159 15519 15566 D SessionLifecycleClient: Sending lifecycle 1 to service
02-06 17:15:28.160 15519 15598 D SessionLifecycleService: Activity foregrounding at 285776108.
02-06 17:15:51.931 15519 15560 D SessionLifecycleClient: Sending lifecycle 2 to service
02-06 17:15:51.931 15519 15598 D SessionLifecycleService: Activity backgrounding at 285799879
02-06 17:15:53.970 15519 16257 I FA      : Application backgrounded at: timestamp_millis: 1707261351964
02-06 17:16:56.171 15519 15560 D SessionLifecycleClient: Sending lifecycle 1 to service
02-06 17:16:56.172 15519 15598 D SessionLifecycleService: Activity foregrounding at 285864120.
02-06 17:17:12.174 15519 15519 D AndroidRuntime: Shutting down VM
02-06 17:17:12.174 15519 15519 E AndroidRuntime: FATAL EXCEPTION: main
02-06 17:17:12.174 15519 15519 E AndroidRuntime: Process: org.nekomanga.neko, PID: 15519
02-06 17:17:12.174 15519 15519 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2466)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1321)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7011)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.View.measure(View.java:27133)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4379)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3270)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:882)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8248)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-06 17:17:12.174 15519 15519 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
02-06 17:17:12.176 15519 15557 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10328; state: ENABLED
02-06 17:17:12.193 15519 15519 I .nekomanga.neko: System.exit called, status: 0
02-06 17:17:12.193 15519 15519 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
02-06 17:17:16.682 16376 16376 W logcat  : type=1400 audit(0.0:68458): avc:  denied  { ioctl } for  path="/storage/emulated/0/Android/data/org.nekomanga.neko/cache/neko_crash_logs.txt" dev="fuse" ino=31106 ioctlcmd=0xf50d scontext=u:r:untrusted_app:s0:c72,c257,c512,c768 tcontext=u:object_r:fuse:s0 tclass=file permissive=0 app=org.nekomanga.neko

### Neko version

2.16

### Android version

Android 13 and 14

### Device

Galaxy Tab S7 & Google Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1691
