### ISSUE TITLE
Library update smart restriction causing Error

### ISSUE THREAD

**Issue by WeebOtaku** [nekomangaorg/Neko#1698]
### Steps to reproduce

Go to Library
Tap Library Update Smart Restrictions
Unexpected Error Code 

### Expected behavior

Remove the smart update 

### Actual behavior

Error happened instead 

### Crash logs

[neko_crash_logs.txt](https://github.com/nekomangaorg/Neko/files/14187498/neko_crash_logs.txt)

### Neko version

2.16

### Android version

Android 14

### Device

Poco F5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by Norsze** [comment]
https://github.com/nekomangaorg/Neko/issues/1691
