### ISSUE TITLE
Crash when trying to access Smart Library Update Restrictions

### ISSUE THREAD

**Issue by yrc64cjgfccdx** [nekomangaorg/Neko#1701]
### Steps to reproduce

Going to Settings > Library > trying to access "Smart Library Update Restrictions" results in immediate crash.

### Expected behavior

Changing filter of manga that were updated under reading status.

### Actual behavior

App crashes with a crash dump prompt.

### Crash logs

[neko_crash_logs.txt](https://github.com/nekomangaorg/Neko/files/14195132/neko_crash_logs.txt)

### Neko version

2.16.0

### Android version

Android 13

### Device

Samsung Note 20 Ultra SM-N986B/DS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1691
