### ISSUE TITLE
Entering the "smart library update restrictions" crashes the app

### ISSUE THREAD

**Issue by Ktlist** [nekomangaorg/Neko#1702]
### Steps to reproduce

1. Enter the config Library/smart library update restrictions
2. Crashed

### Expected behavior

Enter the menu to edit the restrictions for updates

### Actual behavior

Crashes the moment the menu button is pressed

### Crash logs

App version: 2.16.0 (standard, 4107d3dba, 1, 2024-02-06T19:13:30.594121294)
Android version: 13 (SDK 33)
Android build ID: TP1A.220624.014
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: aristotle
Device model: 2306EPN60G
Device product name: aristotle_global
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
at android.widget.AbsListView.obtainView(AbsListView.java:2420)
at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
at android.widget.ListView.onMeasure(ListView.java:1323)
at android.view.View.measure(View.java:26880)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26880)
at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
at android.view.View.measure(View.java:26880)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
at android.view.View.measure(View.java:26880)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26880)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:26880)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:26880)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:840)
at android.view.View.measure(View.java:26880)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4277)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3225)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2647)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9790)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1435)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1443)
at android.view.Choreographer.doCallbacks(Choreographer.java:1052)
at android.view.Choreographer.doFrame(Choreographer.java:944)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1411)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8321)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of system
02-07 14:33:08.013 29536 29536 W Looper  : PerfMonitor looperActivity : package=org.nekomanga.neko/eu.kanade.tachiyomi.ui.main.MainActivity time=0ms latency=324ms running=0ms  procState=-1  historyMsgCount=3
02-07 14:33:08.014 29536 29536 D FramePredict: FramePredict init: false
02-07 14:34:21.636 29536 29536 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
02-07 14:35:36.332 29536 29536 E ActivityThread:  fail in deliverResultsIfNeeded java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
02-07 14:35:36.545 29536 29536 W Activity: PerfMonitor: Slow Operation: Activity org.nekomanga.neko/eu.kanade.tachiyomi.ui.main.MainActivity onActivityResult took 213ms
02-07 14:36:22.660 29536 28472 W BpBinder: Slow Binder: BpBinder transact took 647 ms, interface=android.content.pm.IShortcutService, code=1 oneway=false
02-07 14:36:27.628 29536 28473 W BpBinder: Slow Binder: BpBinder transact took 629 ms, interface=android.content.pm.IShortcutService, code=1 oneway=false
02-07 14:36:32.802 29536 28463 W BpBinder: Slow Binder: BpBinder transact took 201 ms, interface=android.app.INotificationManager, code=7 oneway=false
02-07 14:39:46.977 29536 28463 W BpBinder: Slow Binder: BpBinder transact took 531 ms, interface=android.app.IActivityManager, code=56 oneway=false
--------- beginning of crash
02-07 14:40:21.929 29536 29536 E AndroidRuntime: FATAL EXCEPTION: main
02-07 14:40:21.929 29536 29536 E AndroidRuntime: Process: org.nekomanga.neko, PID: 29536
02-07 14:40:21.929 29536 29536 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2420)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1323)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:840)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4277)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3225)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2647)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9790)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1435)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1443)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1052)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:944)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1411)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:211)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:300)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8321)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
02-07 14:40:21.929 29536 29536 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
02-07 14:40:21.937 29536 29536 W OOMEventManagerFK: Failed to mkdir /data/miuilog/stability/memleak/heapdump/
02-07 14:40:22.221 29570 29570 D FramePredict: FramePredict init: false
02-07 14:40:27.684 29569 29569 D FramePredict: FramePredict init: false
02-07 14:40:35.081 29569 29569 E AndroidRuntime: FATAL EXCEPTION: main
02-07 14:40:35.081 29569 29569 E AndroidRuntime: Process: org.nekomanga.neko, PID: 29569
02-07 14:40:35.081 29569 29569 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2420)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1323)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:840)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4277)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2913)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3225)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2647)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9790)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1435)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1443)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1052)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:944)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1411)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:211)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:300)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8321)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
02-07 14:40:35.081 29569 29569 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
02-07 14:40:35.082 29569 29569 W OOMEventManagerFK: Failed to mkdir /data/miuilog/stability/memleak/heapdump/
02-07 14:40:40.121 29570 29570 W Looper  : PerfMonitor doFrame : time=2ms vsyncFrame=0 latency=431ms procState=-1 historyMsgCount=1
02-07 14:40:44.373   946   946 D FramePredict: FramePredict init: false
02-07 14:41:16.011   946  1028 W BpBinder: Slow Binder: BpBinder transact took 1027 ms, interface=android.content.pm.IShortcutService, code=1 oneway=false
02-07 14:49:40.479   946   946 E AndroidRuntime: FATAL EXCEPTION: main
02-07 14:49:40.479   946   946 E AndroidRuntime: Process: org.nekomanga.neko, PID: 946
02-07 14:49:40.479   946   946 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$1.getView(Unknown Source:10)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2420)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1323)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(SourceFile:151)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.View.measure(View.java:26880)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7136)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 14:49:40.479   946   946 E AndroidRuntime: 	at android.view.View

### Neko version

2.16.0

### Android version

Android 13

### Device

Xiaomi 13T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
https://github.com/nekomangaorg/Neko/issues/1691
