### ISSUE TITLE
smart library udpate click crash

### ISSUE THREAD

**Issue by Thell222** [nekomangaorg/Neko#1706]
### Steps to reproduce

click settings smart library update crash

### Expected behavior

not crash

### Actual behavior

crash

### Crash logs

unexpected error occurred java lang thowable java lang array index out of bounds exception length 7 index 7

### Neko version

newest

### Android version

idk

### Device

lg phone

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Update to 2.16.1
