### ISSUE TITLE
Cant change max downloads in new version

### ISSUE THREAD

**Issue by Thell222** [nekomangaorg/Neko#1708]
### Steps to reproduce

click download many chapters but it only download one at a time

### Expected behavior

download many chapters at same time

### Actual behavior

only one at a time

### Neko version

2.16.1

### Android version

idk

### Device

lg phone

### Other details

before new app it downloaded many now only one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Can you explain what you mean and how you are doing it?

**Comment by Thell222** [comment]
new version only one download at a time old version many at a time
