### ISSUE TITLE
Crashing after new install 

### ISSUE THREAD

**Issue by achilescamilo** [nekomangaorg/Neko#1713]
### Steps to reproduce

After the update, sometimes the app start crashing. Now, I'm not even being able to open  the app.

### Expected behavior

App should open  normally

### Actual behavior

![Screenshot_20240207_191816](https://github.com/nekomangaorg/Neko/assets/36211545/c5b30cec-7418-4cb9-8987-fd7afdbe5096)

### Neko version

2.16.0

### Android version

14

### Device

S23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Update to 2.16.1
