### ISSUE TITLE
Sync MangaDex Follows triggers global update

### ISSUE THREAD

**Issue by TheTabbingman** [nekomangaorg/Neko#1721]
### Steps to reproduce

Sync MangaDex Follows

### Expected behavior

Should sync follows and nothing more

### Actual behavior

After syncing follows, it triggers a global update.

### Neko version

2.16.1

### Android version

Android 14

### Device

Google pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by TheTabbingman** [comment]
Would it be possible to specifically update only the newly synced manga then. Because the category that it syncs to isn't even included in my global update. It could just only update the default category right? because that's the only category it syncs to (unless you previously had the manga on your list, but then it doesn't need an update really). Also does this force an update that ignores the skip metadata option?

**Comment by nonproto** [comment]
Yea that would make more sense, and yes it does force an update that ignores metadata (for the entries that were never initialized)

**Comment by TheTabbingman** [comment]
I updated to 2.16.2 and it is still triggering a global update when i sync.

**Comment by nonproto** [comment]
Its going to trigger an update, the question is did it sync new manga and those updated those?  Or are you saying its updating everything still.

**Comment by TheTabbingman** [comment]
It's still updating everything.
