### ISSUE TITLE
An Unexpected Error Occurred

### ISSUE THREAD

**Issue by Guitarscorpio** [nekomangaorg/Neko#1728]
### Steps to reproduce

Clicking on any manga in the library generates the error

### Expected behavior

open the manga and see the chapter list

### Actual behavior

An Unexpected Error Occurred. Only options are:
- Dump crash logs
- Restart the application
but restart don't solve the crash

### Crash logs

[neko_crash_logs.txt](https://github.com/nekomangaorg/Neko/files/14236244/neko_crash_logs.txt)
![Screenshot_20240212-091229](https://github.com/nekomangaorg/Neko/assets/97180820/9a365342-343c-4e25-be28-05967c5b5f06)

### Neko version

2.16.1

### Android version

Android 10

### Device

Samsung Galaxy Note 9

### Other details

I use a VPN (Proton), but even without it the problem occurs

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by Guitarscorpio** [comment]
Not solved in 2.16.2 ...

**Comment by nonproto** [comment]
> Not solved in 2.16.2 ...

Can you drop another log file/screenshot.

Also where are you are setting your storage at?  Can you try changing to another location?

**Comment by Guitarscorpio** [comment]
Yes! Solved.
Changed the download location from Download to Documents.
In Download/Neko there were 32 folders (from downloads (1) to downloads (32)), all empty.
Thank you!
