### ISSUE TITLE
Download ahead causes page loading stutters on downloaded chapters.

### ISSUE THREAD

**Issue by CaidenBlock** [nekomangaorg/Neko#1733]
### Steps to reproduce

Enable download ahead

Download 2 consecutive chapters of any long strip that has a decent page count (count only makes it more noticeable)

Scroll between pages.

### Expected behavior

Downloading new chapters in background shouldn't cause page loading stutters (like in 2.15.0)

### Actual behavior

Stutters when scrolling between pages of already downloaded chapters

https://github.com/nekomangaorg/Neko/assets/34176510/b1785cec-9fc2-411b-a047-bca67ab77082

### Neko version

2.16.2

### Android version

14

### Device

Google Pixel 7 Pro

### Other details

Repeatable across a fresh install on a Galaxy S22 (also A14), only changes from default are split pages (to make it more noticeable), and download ahead (set to 5)

Neither device does this with the same settings (as far as I can tell) on 2.15.0

I have a feeling this is caused by upstream, but I don't currently use Mihon and didn't see this reported there.
 ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

edit : did some testing in Mihon and did *not* experience this issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by CaidenBlock** [comment]
Less noticeable in the clip I had chosen, but it stutters at the same time the page number on bottom changes, scrolling either up or down.

**Comment by CaidenBlock** [comment]
Expected (2.15.0) behavior:

https://github.com/nekomangaorg/Neko/assets/34176510/77684f1a-c911-426d-8c7a-22a7a72baf4f

**Comment by nonproto** [comment]
Still an issue it seems
