### ISSUE TITLE
Add image proxy mechanism to improve image load times

### ISSUE THREAD

**Issue by galpt** [nekomangaorg/Neko#1736]
### Describe your suggested feature

Please consider adding image proxy feature that can be toggled On/Off.
Some of the available options are:
1. https://wsrv.nl/
2. https://0ms.dev/mirrors/

From the user's perspective, this will improve image load times by acting as an extra caching layer nearest to the user, increasing reliability and performance.

From the manga server's perspective, this will help reducing the burden for frequently requested/downloaded manga titles, as the same images are already cached in optimized servers for caching.

A simple method to benchmark this is by using the browser's **Inspect Elements > "Network" tab**, it will show how much this will improve performance and reliability most of the time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
No plans to add this.  MangaDex has servers all over the world to help with loading as well as @home nodes.  If you really have image loading issues, just download ahead of time, lower the quality, or play with DNS settings in the app.
