### ISSUE TITLE
One-click Auto add trackers in the library/categories 

### ISSUE THREAD

**Issue by TheSeriousYoungBoy** [nekomangaorg/Neko#1745]
### Describe your suggested feature

I'd love it if we can actualise the auto-add-tracker feature when **_opening a title to automatically get trackers for the title/series_** to a _**'You won't need to click all the title/series one by one just to add trackers, you just need to click a single button to make a batch requests to add trackers in each of your title/series in your current library or categories**_.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
If you do settings -> tracking -> refresh tracking metadata.  Does it add them all?

**Comment by TheSeriousYoungBoy** [comment]
> If you do settings -> tracking -> refresh tracking metadata.  Does it add them all?

No, it doesn't, unfortunately.

**Comment by nonproto** [comment]
I just double checked and it definitely does. However you have to have loaded the manga.  So if you just long press added a manga and it never loaded, neko doesn't have the tracking id associated on MangaDex, so can't add the tracker.
