### ISSUE TITLE
AniList tracking not work for manga "Kimi no Tame nara Shineru"

### ISSUE THREAD

**Issue by Anselmo0454** [nekomangaorg/Neko#1748]
### Steps to reproduce

1. searching for "Kimi no Tame nara Shineru"
2. Open AL tracking

### Expected behavior

Once I open the AL tracker it should synchronize the manga with my AniList profile.

### Actual behavior

What actually happens is that it does not find the manga on AniList. Yet, it is present in the database (https://anilist.co/manga/59743/Kimi-no-Tame-nara-Shineru/). 

Also, another problem is that besides not finding the manga in question, is that it does not find anything else as if nothing exists. 

### Neko version

2.16.2

### Android version

Android 13

### Device

Xiaomi POCO X5 Pro 5G

### Other details

I tried refreshing the entry, removing and adding back to the library. Nothing has changed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Ah i see the issue.
https://mangadex.org/title/89fc8249-939e-4b37-b1a3-8a7d1a9288e8/kimi-no-tame-nara-shineru  
the anilist url is wrong, opening a report on mangadex
