### ISSUE TITLE
Notify user when logged out of MangaDex

### ISSUE THREAD

**Issue by sopoforic** [nekomangaorg/Neko#1749]
### Describe your suggested feature

If I become logged out of mangadex (e.g. when the token expires), Neko should prominently notify me of this fact. Ideally, the notification would let me directly sign back into mangadex, without having to navigate through the settings first.

### Other details

It's important to me that the chapters I read are synced back to mangadex, and if I become logged out without noticing (which is every time, since it's invisible when this happens), then I must go through my history and fix the chapters' read status. A simple notification that I need to log in again would solve this problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by alidan** [comment]
On the topic of telling us when we log out, if that's not possible, would it be possible to take note of when chapters lose the ability to submit tracking data, and then when we log in, preset us with the ability to submit? this would be helpful across all methods of tracking chapters.
