### ISSUE TITLE
Search filters 

### ISSUE THREAD

**Issue by hullmat998** [nekomangaorg/Neko#1760]
### Describe your suggested feature

If there is a way; I would love the ability to filter out series by country of origin, and also those without chapters. Too often when I'm browsing genres like "cooking" the majority of the titles have zero chapters. Other ones are from Korea, US, or China; which I'm tend to avoid like the plague. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
This is already doable.  Open up the search filter, select `original language` dropdown and select `Japanese`, then close that drop down and select `other` and then click `has available chapters` now save this filter, then click the heart next to the saved filter.  

This will default those filters always on, so now when you click genre and say cooking it will in include the defaults above
