### ISSUE TITLE
Multiple Crashings

### ISSUE THREAD

**Issue by MeyMan2007** [nekomangaorg/Neko#1761]
### Steps to reproduce

I can't even open the app without seeing the bug screen.

### Expected behavior

It should work just fine

### Actual behavior

It crashed

### Crash logs

App version: 2.16.2 (standard, dd9636037, 3, 2024-02-16T14:31:37.626086128)
Android version: 12 (SDK 31)
Android build ID: RMX3241_11_C.03
Device brand: realme
Device manufacturer: realme
Device name: RE513CL1
Device model: RMX3241
Device product name: RMX3241EEA
           ******************************************************************************************************************************************************************************************************************************
           Exception that caused crash
           ******************************************************************************************************************************************************************************************************************************
           java.lang.Throwable: android.database.sqlite.SQLiteFullException: database or disk is full (code 13 SQLITE_FULL)
at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:709)
at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:589)
at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(Unknown Source:2)
at androidx.room.RoomDatabase.internalEndTransaction(SourceFile:9)
at androidx.core.provider.CallbackWithHandler.insertPreference(SourceFile:33)
at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(SourceFile:613)
at androidx.work.impl.utils.ForceStopRunnable.run(SourceFile:29)
at androidx.work.Worker$2.run(SourceFile:257)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)

           ******************************************************************************************************************************************************************************************************************************
           ******************************************************************************************************************************************************************************************************************************--------- beginning of system
03-13 00:47:22.402 26104 26104 I Quality : Skipped: true 1 cost 17.9281 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:47:42.618 26104 26104 I Quality : Skipped: true 1 cost 16.368948 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:47:54.261 26104 26104 I Quality : Skipped: true 1 cost 20.924194 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:48:32.126 26104 26104 I Quality : Skipped: false 1 cost 12.060344 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:48:57.383 26104 26104 I Quality : Skipped: false 1 cost 13.323703 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:48:57.459 26104 26104 I Quality : Skipped: false 6 cost 67.23663 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:48:57.488 26104 26104 I Quality : Skipped: false 1 cost 17.143864 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:48:57.504 26104 26104 I Quality : Skipped: false 1 cost 11.2157545 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:48:58.355 26104 26104 I Quality : Skipped: false 1 cost 15.955282 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:49:22.479 26104 26104 I Quality : Skipped: true 1 cost 11.457137 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:49:53.907 26104 26104 I Quality : Skipped: true 2 cost 32.282993 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:49:54.864 26104 26104 I Quality : Skipped: true 1 cost 17.675999 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:06.412 26104 26104 I Quality : Skipped: true 1 cost 12.376528 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:47.323 26104 26104 I Quality : Skipped: false 2 cost 24.309597 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:48.912 26104 26104 I Quality : Skipped: false 2 cost 22.544922 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:48.957 26104 26104 I Quality : Skipped: false 3 cost 34.562756 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:48.982 26104 26104 I Quality : Skipped: false 1 cost 14.9052 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:49.357 26104 26104 I Quality : Skipped: true 1 cost 12.461209 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:50.902 26104 26104 I Quality : Skipped: false 4 cost 46.325367 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:55.706 26104 26104 I Quality : ActivityThread: activityStart delay 56 org.nekomanga.neko 26104
03-13 00:50:55.717 26104 26104 I Quality : Skipped: false 5 cost 65.51249 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:55.760 26104 26104 I Quality : Skipped: false 3 cost 36.497257 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:55.795 26104 26104 I Quality : Skipped: false 1 cost 16.276602 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:55.835 26104 26104 I Quality : Skipped: false 2 cost 33.235165 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:55.884 26104 26104 I Quality : Skipped: false 2 cost 26.95311 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:59.388 26104 26104 I Quality : Skipped: false 2 cost 22.496052 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:50:59.660 26104 26104 I Quality : Skipped: false 2 cost 24.982143 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:51:01.690 26104 26104 I Quality : Skipped: false 1 cost 15.1413355 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:51:01.726 26104 26104 I Quality : Skipped: false 1 cost 18.057213 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:51:02.371 26104 26104 I Quality : Skipped: false 6 cost 74.09794 refreshRate 11111111 processName org.nekomanga.neko
03-13 00:51:02.686 26104 26104 I Quality : Skipped: false 1 cost 11.156865 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:06.181  3986  3986 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
03-13 01:21:06.279  3986  3986 I Quality : ActivityThread: viewInflate delay 119 org.nekomanga.neko:layout/main_activity 3986
03-13 01:21:06.406  3986  3986 I Quality : ActivityThread: activityStart delay 274 org.nekomanga.neko 3986
03-13 01:21:06.449  3986  3986 I Quality : Skipped: false 48 cost 536.71436 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:06.656  3986  3986 I Quality : Skipped: false 17 cost 198.97359 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:06.687  3986  3986 I Quality : Skipped: false 2 cost 29.724716 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:06.712  3986  3986 I Quality : Skipped: false 1 cost 21.15136 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:07.824  3986  3986 I Quality : Skipped: false 23 cost 266.39993 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:07.873  3986  3986 I Quality : Skipped: false 3 cost 37.25642 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:10.764  3986  3986 I Quality : Skipped: false 2 cost 22.617712 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:10.864  3986  3986 I Quality : Skipped: false 8 cost 89.80138 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:10.920  3986  3986 I Quality : Skipped: false 1 cost 11.19804 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:11.351  3986  3986 I Quality : Skipped: false 19 cost 219.74303 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:11.449  3986  3986 I Quality : Skipped: false 8 cost 95.49283 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:11.470  3986  3986 I Quality : Skipped: false 1 cost 16.49046 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:11.568  3986  3986 I Quality : Skipped: false 6 cost 70.50983 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:11.599  3986  3986 I Quality : Skipped: false 2 cost 22.781136 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:11.827  3986  3986 I Quality : Skipped: false 2 cost 28.305048 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:12.040  3986  3986 I Quality : Skipped: false 1 cost 18.989008 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:12.087  3986  3986 I Quality : Skipped: false 2 cost 27.69376 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:12.151  3986  3986 I Quality : Skipped: true 3 cost 36.06307 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:12.193  3986  3986 I Quality : Skipped: false 1 cost 11.773257 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:12.778  3986  3986 I Quality : Skipped: false 1 cost 18.037384 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:14.083  3986  3986 I Quality : Skipped: true 13 cost 152.71562 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:14.108  3986  3986 I Quality : Skipped: false 2 cost 24.510427 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:14.439  3986  3986 I Quality : Skipped: false 3 cost 43.487675 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:26.309  3986  3986 I Quality : Skipped: false 1 cost 11.180685 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:29.148  3986  3986 I Quality : Skipped: false 1 cost 17.619543 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:29.413  3986  3986 I Quality : Skipped: false 1 cost 14.17004 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:31.081  3986  3986 I Quality : Skipped: false 13 cost 145.32756 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:31.107  3986  3986 I Quality : Skipped: false 1 cost 16.339027 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:31.212  3986  3986 I Quality : Skipped: false 4 cost 47.673035 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:31.239  3986  3986 I Quality : Skipped: true 1 cost 18.739466 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:31.410  3986  3986 I Quality : Skipped: false 1 cost 12.07852 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:34.752  3986  3986 I Quality : ActivityThread: activityStart delay 104 org.nekomanga.neko 3986
03-13 01:21:34.770  3986  3986 I Quality : Skipped: false 10 cost 113.83906 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:34.841  3986  3986 I Quality : Skipped: false 5 cost 63.045128 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:34.870  3986  3986 I Quality : Skipped: false 2 cost 24.8222 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:34.917  3986  3986 I Quality : Skipped: false 3 cost 38.767544 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:35.269  3986  3986 I Quality : Skipped: false 1 cost 13.091602 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:35.363  3986  3986 I Quality : Skipped: false 1 cost 17.61302 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:35.702  3986  3986 I Quality : Skipped: false 1 cost 12.298863 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:35.725  3986  3986 I Quality : Skipped: false 1 cost 12.950522 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:43.584  3986  3986 I Quality : Skipped: false 8 cost 97.884705 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:43.613  3986  3986 I Quality : Skipped: false 2 cost 27.507212 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:43.864  3986  3986 I Quality : Skipped: true 2 cost 22.565926 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:44.488  3986  3986 I Quality : Skipped: false 6 cost 70.14536 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:44.962  3986  3986 I Quality : Skipped: false 3 cost 42.705265 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:45.196  3986  3986 I Quality : Skipped: false 20 cost 232.89767 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:45.236  3986  3986 I Quality : Skipped: false 3 cost 39.149834 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:45.514  3986  3986 I Quality : Skipped: false 1 cost 16.608133 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:45.801  3986  3986 I Quality : Skipped: false 1 cost 20.988728 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:45.891  3986  3986 I Quality : Skipped: false 1 cost 21.843287 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:48.912  3986  3986 I Quality : Skipped: false 5 cost 59.145214 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:48.972  3986  3986 I Quality : Skipped: false 1 cost 12.350985 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:49.569  4927  4927 I Quality : ActivityThread: activityStart delay 50 org.nekomanga.neko:error_handler 4927
03-13 01:21:49.621  4927  4927 I Quality : Skipped: false 2 cost 27.480324 refreshRate 11111111 processName org.nekomanga.neko:error_handler
03-13 01:21:49.860  4927  4927 I Quality : Skipped: false 20 cost 233.02147 refreshRate 11111111 processName org.nekomanga.neko:error_handler
03-13 01:21:52.709  4927  4927 I Quality : Skipped: false 2 cost 23.499304 refreshRate 11111111 processName org.nekomanga.neko:error_handler
03-13 01:21:53.089  5001  5001 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
03-13 01:21:53.195  5001  5001 I Quality : ActivityThread: viewInflate delay 127 org.nekomanga.neko:layout/main_activity 5001
03-13 01:21:53.292  5001  5001 I Quality : ActivityThread: activityStart delay 246 org.nekomanga.neko 5001
03-13 01:21:53.326  5001  5001 I Quality : Skipped: false 37 cost 413.0995 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:53.463  5001  5001 I Quality : Skipped: false 11 cost 127.41958 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:53.534  5001  5001 I Quality : Skipped: false 5 cost 64.838844 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:53.771  5001  5001 I Quality : Skipped: false 20 cost 224.59341 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:53.973  5001  5001 I Quality : Skipped: false 17 cost 192.88701 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:54.020  5001  5001 I Quality : Skipped: false 2 cost 29.052689 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:54.051  5001  5001 I Quality : Skipped: false 2 cost 26.020535 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:54.093  5001  5001 I Quality : Skipped: false 3 cost 35.061764 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:55.027  5001  5001 I Quality : Skipped: false 4 cost 46.343174 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:55.122  5001  5001 I Quality : Skipped: false 7 cost 84.968605 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:55.143  5001  5001 I Quality : Skipped: false 1 cost 17.411095 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:55.837  5001  5001 I Quality : Skipped: false 10 cost 111.285385 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:56.059  5001  5001 I Quality : Skipped: false 18 cost 210.7375 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:56.149  5001  5001 I Quality : Skipped: false 7 cost 78.56437 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:56.253  5001  5001 I Quality : Skipped: false 8 cost 99.65648 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:56.461  5001  5001 I Quality : Skipped: false 17 cost 196.34325 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:56.599  5001  5001 I Quality : Skipped: false 12 cost 133.85155 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:56.620  5001  5001 I Quality : Skipped: false 1 cost 15.844362 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:56.650  5001  5001 I Quality : Skipped: false 2 cost 23.815416 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.467  5001  5001 I Quality : ActivityThread: activityStart delay 86 org.nekomanga.neko 5001
03-13 01:21:59.481  5001  5001 I Quality : Skipped: false 10 cost 113.37395 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.525  5001  5001 I Quality : Skipped: false 3 cost 35.299515 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.545  5001  5001 I Quality : Skipped: false 1 cost 11.196039 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.599  5001  5001 I Quality : Skipped: false 3 cost 42.104652 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.638  5001  5001 I Quality : Skipped: false 3 cost 36.683464 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.668  5001  5001 I Quality : Skipped: false 2 cost 22.82977 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.784  5001  5001 I Quality : Skipped: false 2 cost 27.816614 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:21:59.806  5001  5001 I Quality : Skipped: false 1 cost 16.188028 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:22:00.070  5001  5001 I Quality : Skipped: false 13 cost 146.62572 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:22:00.267  5001  5001 I Quality : Skipped: false 1 cost 21.541348 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:22:00.598  5001  5001 I Quality : Skipped: false 1 cost 19.016771 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:22:00.938  5001  5001 I Quality : Skipped: false 1 cost 13.829284 refreshRate 11111111 processName org.nekomanga.neko
03-13 01:22:02.181  5001  5001 I Quality : Skipped: false 1 cost 11.854736 refreshRate 11111111 processName org.nekomanga.neko
--------- beginning of crash
03-13 01:22:02.828  5001  5001 E AndroidRuntime: FATAL EXCEPTION: main
03-13 01:22:02.828  5001  5001 E AndroidRuntime: Process: org.nekomanga.neko, PID: 5001
03-13 01:22:02.828  5001  5001 E AndroidRuntime: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.execute(Unknown Source:30)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteSession.endTransactionUnchecked(Unknown Source:62)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteSession.endTransaction(Unknown Source:4)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteDatabase.endTransaction(Unknown Source:8)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$LowLevelImpl.endTransaction(SourceFile:9)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.saveReadingProgress(SourceFile:21)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderViewModel.onBackPressed(SourceFile:37)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.reader.ReaderActivity.finishAfterTransition(SourceFile:38)
03-13 01:22:02.828  5001  5001 E AndroidRuntime: 	at android.app.Activity.onBackPressed(Activity.java:3945)
03-13 01:22:02.828  5001  5001 E Andr

### Neko version

2.16.2

### Android version

Android 12

### Device

Realme 8 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Do you have any storage available on your device?  Try clearing the app's cache

**Comment by MeyMan2007** [comment]
> Do you have any storage available on your device?  Try clearing the app's cache

Yes, I tried, but it still didn't work

**Comment by nonessentialprototype** [comment]
Do you have storage available?  This error means the DB can't write due to storage issues

**Comment by nonproto** [comment]
Do you have any storage that error is complaining about available storage

**Comment by nonproto** [comment]
Clear up your storage
