### ISSUE TITLE
App crashes when opening manga details page

### ISSUE THREAD

**Issue by gcpadua** [nekomangaorg/Neko#1776]
### Steps to reproduce

1- On any page from the app, be it recents, library or search page search for "Mushoku Tensei Isekai Ittara Honki Dasu"
2- Open the page for the above mentioned manga
3- The app crashes

### Expected behavior

The app shouldn't crash

### Actual behavior

The app crashes

### Crash logs

[neko_crash_logs.txt](https://github.com/nekomangaorg/Neko/files/14720846/neko_crash_logs.txt)

### Neko version

App version: 2.16.3

### Android version

Android version: 13 (SDK 33)

### Device

Samsung Galaxy S20 FE (SM-G780F)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Can you try now?  I think there was bad data on mangadex because this works fine for me

**Comment by gcpadua** [comment]
It doesn't crash when I open the page now but the chapter list is empty. Info about the manga is there like the title, description, tags and alt titles.

**Comment by nonproto** [comment]
you could have just swipe refreshed the manga detail page.

**Comment by gcpadua** [comment]
It also crashed when I swipe refreshed
