### ISSUE TITLE
Mangadex token null

### ISSUE THREAD

**Issue by BioGhosty** [nekomangaorg/Neko#1799]
### Steps to reproduce

1. Be using the app
2. Every so often, typically every 24-48 hours, Neko will have a toast notification saying the the Mangadex sign in token is null and you will need to log back in

### Expected behavior

Should be able to be stayed logged in for more than 48 hours, like in previous releases

### Actual behavior

Need to log back in to Mangadex every 48 hours or so

### Neko version

Stable 2.16.4

### Android version

Android 14

### Device

Google Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
The token being null, is because neko removes it. It only removes it if it fails to refresh the token.  It definitely is not something every 48h unless MangaDex is revoking tokens as i have been logged in for longer than that.

**Comment by nonproto** [comment]
Also the toast is just a visual representation of what was previously already happening
