### ISSUE TITLE
Downloaded chapters will redownload.

### ISSUE THREAD

**Issue by rocketlawnchair** [nekomangaorg/Neko#1806]
### Steps to reproduce

Will happen randomly while reading a manga while offline. i cant get it to reproduce 100% of the time. 

### Expected behavior

images should load from download folder.

### Actual behavior

The app will try to redownload chapters while off wifi or offline. if you leave and come back to the chapter you were reading. it will not load.
![Screenshot_20240426_074100](https://github.com/nekomangaorg/Neko/assets/17911803/0d0ddb8b-00be-4eab-801c-ea397efb6d81)
![Screenshot_20240426_074042](https://github.com/nekomangaorg/Neko/assets/17911803/a8821efd-ad12-4fd3-be76-abfc763e62d4)
![Screenshot_20240426_074555](https://github.com/nekomangaorg/Neko/assets/17911803/13030e47-5602-4642-b86a-0ea74968aeb0)
![Screenshot_20240426_092514_Messages](https://github.com/nekomangaorg/Neko/assets/17911803/3e0533ca-c73c-4f07-b692-dcea54b364eb)

https://github.com/nekomangaorg/Neko/assets/17911803/571861bb-6578-4326-a699-154e1fa3b3a0

### Neko version

2.16.5

### Android version

Android 14

### Device

Samsung Galaxy S24+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Can you check your file explorer and see if there are duplicate folders for those chapters?
Send a screen if there are

**Comment by rocketlawnchair** [comment]
i believe the whole manga is merged.

**Comment by nonproto** [comment]
I meant is it only MangaLife chapters that do this redownload?  If so its likely the url is changing and so its being seen as a new chapter.

**Comment by rocketlawnchair** [comment]
I only have mangalife as my source. So I can't give you a control group for a second one.

**Comment by nonproto** [comment]
So you have no manga that you read with Dex chapters?

**Comment by rocketlawnchair** [comment]
Sorry. Not currently. I'll try to keep a few versions for when the big shows up again.

**Comment by chichibooxd** [comment]
Can confirm here too. I got the latest update and downloaded chapters sometimes stop loading and start redownloading. I only use Dex as source so it's def an app issue.

**Comment by Efreak** [comment]
They try to redownload while online as well. If I cancel downloading a chapter that's already been downloaded, these chairs show as no longer being downloaded and I have to wait for it to fetch the online version. This is particularly annoying on some web toons that use extremely short sections (900+ images per chapter on one I read recently, I eventually gave up and dropped that one because I could read 3 chapters in the time it took to download one)
