### ISSUE TITLE
sorting with latest uploads is not latest

### ISSUE THREAD

**Issue by wispold** [nekomangaorg/Neko#1827]
### Steps to reproduce

I only want latest Japanese original language mangos so i used the search function. after filtering with language and checking latest uploads it even shows me results from 2023. 

https://github.com/nekomangaorg/Neko/assets/59336106/c3e65628-7d4f-4cd8-9125-1336d9d1f643

### Expected behavior

should show latest updates

### Actual behavior

but it's not latest 

### Neko version

2.16.7

### Android version

Android 14

### Device

Xiaomi 11t

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
latest uploads is based on chapter upload date.  You need to sort by `Recently Added` if you are looking for new manga just added.

**Comment by wispold** [comment]
i wasn't looking for recently added ones. but maybe it's sorting without language filter that even though it's listed as latest i am only seeing old dates with english chapters?

**Comment by nonproto** [comment]
that is a limitation of the api
