### ISSUE TITLE
Unnable to download chapters

### ISSUE THREAD

**Issue by FaradaayV11** [nekomangaorg/Neko#1830]
### Steps to reproduce

Whenever i try to download any chapter from any manga i recieve the following error message "invalid download location".
What i tried to do so far: 
- Create a new dedicated folder and set it as storage location, this however didn't solve the problem.
- Unninstaling the app and installing it again, wish also did not solve the problem.
![20240519_131624](https://github.com/nekomangaorg/Neko/assets/170256461/0c2026e0-644c-45e7-8ac9-1277ced9cb85)

### Expected behavior

The chapter should be downloaded

### Actual behavior

The chapter does not download 

### Neko version

2.16.7

### Android version

Android 10

### Device

Galaxy S9+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Are you still having this issue?

**Comment by FaradaayV11** [comment]
I managed to solve the issue by reverting the app back to version 2.16.6. 
By doing that i was able to download chapters again, however i didn't try to update the app to the latest version after that happended.
