### ISSUE TITLE
Can't read or download mangaplus chapters

### ISSUE THREAD

**Issue by snarkyyy** [nekomangaorg/Neko#1848]
### Steps to reproduce

Try to open in the in-app reader any chapter provided by mangaplus
Or try to download such chapter

### Expected behavior

Chapter opened for reading
or chapter files downloaded to local storage

### Actual behavior

"The image couldn't be loaded"
or chapter downloads successfully but every page is empty

### Neko version

2.16.7

### Android version

Android 14

### Device

Google Pixel 6a

### Other details

I tried to clear all app data and reinstall, the issue still persists.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by DreiPixel** [comment]
Same Issue here. the images are saved as jpeg but they cannot be opened with anything. tried several different programs.

**Comment by Malavisto** [comment]
A temporary fix, I've used is merging with manga4life (ML) then downloading the chapters so that might help with your problem
