### ISSUE TITLE
Neko crashes whenever i set the cover for a manga or manhwa

### ISSUE THREAD

**Issue by Repovk** [nekomangaorg/Neko#1854]
### Steps to reproduce

Try setting the cover of any manga or manhwa

### Expected behavior

The cover should be set to whatever vol. cover was chosen

### Actual behavior

Neko crashes when you set a cover due to open failed: eacess (permission denied)

### Crash logs

![Screenshot_2024-06-27-12-18-25-42_47a67ab7be25a408169669ae038dff2d](https://github.com/nekomangaorg/Neko/assets/173868238/334acee5-52a3-47a0-ba66-06fd81d3a973)

### Neko version

2.16.7

### Android version

Android 14

### Device

Realme C55

### Other details

I heard a fix for this is granting the necessary permission to access the data folder where the covers are located but the new Android update doesn't allow apps to be granted a permission unless the app requested it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Is this an sd card?  Its writing to a location the app should have permissions to

**Comment by Repovk** [comment]
> Is this an sd card? Its writing to a location the app should have permissions to

No it's directly on the internal storage, my phone's manufacturer doesn't allow apps on the external storage

**Comment by nonproto** [comment]
really weird, is it from the artwork screen, or is it a page?

**Comment by nonproto** [comment]
Do you still have this issue on  2.16.9
