### ISSUE TITLE
Crashes when opening manga info

### ISSUE THREAD

**Issue by Iammaduk** [nekomangaorg/Neko#1859]
### Steps to reproduce

1. Click any manga
2. Crash

### Expected behavior

Load the manga information / open recent chapter

### Actual behavior

Crashes

### Crash logs

![Screenshot_20240627_231952](https://github.com/nekomangaorg/Neko/assets/174066843/e626363b-d637-48e0-99e8-7c993953b67f)

### Neko version

It crashes when viewing, but the most recent version

### Android version

12

### Device

Samsung s8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1857

**Comment by nonproto** [comment]
fixed in 2.16.9  you may need to manually update
