### ISSUE TITLE
Crash on search in Browse

### ISSUE THREAD

**Issue by InkyQuill** [nekomangaorg/Neko#1861]
### Steps to reproduce

1. Update to 2.16.9
2. Open browse
3. Tap on search

### Expected behavior

Open search panel

### Actual behavior

Crash. 
![Screenshot_20240628_065531](https://github.com/nekomangaorg/Neko/assets/16044715/5e02584f-b0ae-4b7e-abf4-1c8933f5324a)
![Screenshot_20240628_065541](https://github.com/nekomangaorg/Neko/assets/16044715/efd809b7-2b29-4dea-a209-67970eb52f65)
![Screenshot_20240628_065555](https://github.com/nekomangaorg/Neko/assets/16044715/6c3949ad-f799-4dce-9b8d-b653255717af)

### Neko version

2.16.9

### Android version

14

### Device

Samsung S23 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by InkyQuill** [comment]
Somehow can't upload crash logs, be it TXT or Zipped version. It is too big to get in the field as well.

https://pastebin.com/WpkJcPVD

**Comment by InkyQuill** [comment]
Seems like deserialization issue for saved searches. Can those searches be cleared without clearing the whole library?

**Comment by InkyQuill** [comment]
Seems that the culprit is commit ba469cb
Maybe a data converter or fallback deserializer could be implemented?

**Comment by Wolf-ON** [comment]
> Can those searches be cleared without clearing the whole library?

Yes, they can. `Settings -> MangaDex Settings -> Delete saved filters`

**Comment by nonproto** [comment]
Yep you need to delete your saved filters. Like wolf said.

**Comment by InkyQuill** [comment]
Can confirm as the solution.
