### ISSUE TITLE
App always crash when trying to search for manga

### ISSUE THREAD

**Issue by EricFoodTab** [nekomangaorg/Neko#1863]
### Steps to reproduce

1. Press the search button in the app
2. Crash log appear

### Expected behavior

It should've let me search for manga

### Actual behavior

Neko crashes everytime i try to search for a manga

### Crash logs

[nekocrashlog.pdf](https://github.com/user-attachments/files/16028423/nekocrashlog.pdf)

### Neko version

2.16.9

### Android version

Android 13

### Device

Xiaomi Pad 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by InkyQuill** [comment]
Clear saved filters. Had the same issue #1861
