### ISSUE TITLE
App crash when using search

### ISSUE THREAD

**Issue by AshkanZirakzadeh** [nekomangaorg/Neko#1864]
### Steps to reproduce

1. Open the app
2. Go to the browse tab at the bottom
3. Press Search

### Expected behavior

Search should open

### Actual behavior

The app crashes with an error mentioning the ECCHI tag

![Screenshot_20240628_192657](https://github.com/nekomangaorg/Neko/assets/22134504/dc6a62da-979b-4b32-b85a-a5c6297effee)

### Crash logs

[neko_crash_logs.txt](https://github.com/user-attachments/files/16037496/neko_crash_logs.txt)

### Neko version

2.16.9

### Android version

android 13

### Device

Samsung S20+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
https://github.com/nekomangaorg/Neko/issues/1863
