### ISSUE TITLE
Crash when navigating to search

### ISSUE THREAD

**Issue by lilydull** [nekomangaorg/Neko#1867]
### Steps to reproduce

1. Open app
2. Press browse
3. Press search

### Expected behavior

It opens the page where I can search for manga

### Actual behavior

The app crashes as soon as I press the search button.

https://github.com/nekomangaorg/Neko/assets/168235855/816aac08-df96-4513-a0e6-62b27e1a1934

### Crash logs

[neko_crash_logs.txt](https://github.com/user-attachments/files/16040878/neko_crash_logs.txt)

### Neko version

2.16.9

### Android version

Android 13

### Device

OnePlus 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1861
