### ISSUE TITLE
Neko crashed everytime when using search

### ISSUE THREAD

**Issue by pelusinc** [nekomangaorg/Neko#1868]
### Steps to reproduce

1. Open neko
2. Tap browse
3. Tap search 
4. It will crash

### Expected behavior

Expect to open search functionality

### Actual behavior

It will not open search, but crash

### Crash logs

[neko_crash_logs.txt](https://github.com/user-attachments/files/16043979/neko_crash_logs.txt)

### Neko version

2.16.9

### Android version

Android 13

### Device

Redmi note 11 pro 5g

### Other details

![Screenshot_2024-06-30-17-25-06-919_org nekomanga neko](https://github.com/nekomangaorg/Neko/assets/61071770/9a4fb495-4373-45a3-89c9-87e4dfa97814)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1861
