### ISSUE TITLE
App crash after tapping search button

### ISSUE THREAD

**Issue by aruto77** [nekomangaorg/Neko#1871]
### Steps to reproduce

1. Open Neko App
2. Select Browse tab
3. Tap Search button

### Expected behavior

After tapping search button it should open menu for searching certain comic based on filter

### Actual behavior

Sending error message logs and after restarting the app the issue still exist

### Crash logs

[neko_crash_logs.txt](https://github.com/user-attachments/files/16048285/neko_crash_logs.txt)

### Neko version

2.16.9

### Android version

Android 12

### Device

POCO X3 NFC

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
#1861
