### ISSUE TITLE
Search crashes my app

### ISSUE THREAD

**Issue by Salox** [nekomangaorg/Neko#1876]
### Steps to reproduce

Load, browse, then search,

### Expected behavior

Load sheaxh

### Actual behavior

Crash

### Crash logs

App version: 2.16.9 (standard, b6d958781, 10, 2024-06-28T00:51:12.841592104)
Android version: 13 (SDK 33)
Android build ID: T1SHS33.35-23-22-11
Device brand: motorola
Device manufacturer: motorola
Device name: hiphi
Device model: motorola edge plus (2022)
Device product name: hiphi_gu
--------- beginning of system
07-03 09:36:50.038 21584 21584 D ViewRootImpl: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:36:50.038 21584 21584 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:36:50.038 21584 21584 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-03 09:36:50.038 21584 21584 D ViewRootImpl:   bhv=DEFAULT
07-03 09:36:50.038 21584 21584 D ViewRootImpl:   fitSides=} by setView
07-03 09:36:55.115 21584 21584 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:36:55.115 21584 21584 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:36:55.115 21584 21584 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-03 09:36:55.115 21584 21584 D VRI[MainActivity]:   bhv=DEFAULT
07-03 09:36:55.115 21584 21584 D VRI[MainActivity]:   fitSides=} by setLayoutParams
07-03 09:36:58.406 21836 21836 D ViewRootImpl: update {(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:36:58.406 21836 21836 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:36:58.406 21836 21836 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-03 09:36:58.406 21836 21836 D ViewRootImpl:   bhv=DEFAULT
07-03 09:36:58.406 21836 21836 D ViewRootImpl:   fitSides=} by setView
07-03 09:37:12.903 21836 21836 D VRI[CrashActivity]: update {(0,0)(fillxfill) sim={adjust=pan forwardNavigation} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:37:12.903 21836 21836 D VRI[CrashActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:37:12.903 21836 21836 D VRI[CrashActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST FIT_INSETS_CONTROLLED
07-03 09:37:12.903 21836 21836 D VRI[CrashActivity]:   bhv=DEFAULT
07-03 09:37:12.903 21836 21836 D VRI[CrashActivity]:   fitSides=} by setLayoutParams
--------- beginning of main
07-03 09:39:27.930 22313 22313 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
07-03 09:39:28.002 22313 22313 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10137; state: ENABLED
07-03 09:39:28.034 22313 22313 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10137; state: ENABLED
07-03 09:39:28.083 22313 22376 E SQLiteLog: (284) automatic index on C(manga_id)
07-03 09:39:28.083 22313 22376 E SQLiteLog: (284) automatic index on R(manga_id)
07-03 09:39:28.083 22313 22376 E SQLiteLog: (284) automatic index on B(manga_id)
07-03 09:39:28.083 22313 22376 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
07-03 09:39:28.091 22313 22352 D SessionLifecycleClient: Sending lifecycle 1 to service
07-03 09:39:28.092 22313 22374 D SessionLifecycleService: Activity foregrounding at 252148026.
07-03 09:39:28.092 22313 22374 D SessionLifecycleService: Cold start detected.
07-03 09:39:28.092 22313 22374 D SessionLifecycleService: Generated new session 46228b8bc22044aaa9387f7d015dc687
07-03 09:39:28.092 22313 22374 D SessionLifecycleService: Broadcasting new session: SessionDetails(sessionId=46228b8bc22044aaa9387f7d015dc687, firstSessionId=46228b8bc22044aaa9387f7d015dc687, sessionIndex=0, sessionStartTimestampUs=1720013968092000)
07-03 09:39:28.093 22313 23771 I FA      : Tag Manager is not found and thus will not be used
07-03 09:39:28.093 22313 22356 D SessionFirelogPublisher: Data Collection is enabled for at least one Subscriber
07-03 09:39:28.095 22313 22313 D ViewRootImpl: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:39:28.095 22313 22313 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:39:28.095 22313 22313 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-03 09:39:28.095 22313 22313 D ViewRootImpl:   bhv=DEFAULT
07-03 09:39:28.095 22313 22313 D ViewRootImpl:   fitSides=} by setView
07-03 09:39:28.104 22313 22344 D EventGDTLogger: Session Event: {"eventType":1,"sessionData":{"sessionId":"46228b8bc22044aaa9387f7d015dc687","firstSessionId":"46228b8bc22044aaa9387f7d015dc687","sessionIndex":0,"eventTimestampUs":1720013968092000,"dataCollectionStatus":{"performance":1,"crashlytics":2,"sessionSamplingRate":1.0},"firebaseInstallationId":"cLrpkftlT5qGreX4HgB7Tu","firebaseAuthenticationToken":"eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6NDU4ODUyMzQ0NzM5OmFuZHJvaWQ6ZTAzNDkzMjk5NzVhZWY3ZWIzNzAxNiIsImV4cCI6MTcyMDU2NTY5MywiZmlkIjoiY0xycGtmdGxUNXFHcmVYNEhnQjdUdSIsInByb2plY3ROdW1iZXIiOjQ1ODg1MjM0NDczOX0.AB2LPV8wRgIhAJX_KHo-FD7umfvQ_Weiebm6TjKqj91UcxkJUyLHnJgdAiEA-LZ8QeQwc3JGGSQZcbyQBltouFAy67nvdDon5xIG4hI"},"applicationInfo":{"appId":"1:458852344739:android:e0349329975aef7eb37016","deviceModel":"motorola edge plus (2022)","sessionSdkVersion":"2.0.2","osVersion":"13","logEnvironment":3,"androidAppInfo":{"packageName":"org.nekomanga.neko","versionName":"2.16.9","appBuildVersion":"10","deviceManufacturer":"motorola","currentProcessDetails":{"processName":"org.nekomanga.neko","pid":22313,"importance":100,"defaultProcess":true},"appProcessDetails":[{"processName":"org.nekomanga.neko","pid":22313,"importance":100,"defaultProcess":true},{"processName":"org.nekomanga.neko:error_handler","pid":21836,"importance":400,"defaultProcess":false}]}}}
07-03 09:39:28.104 22313 22344 D SessionFirelogPublisher: Successfully logged Session Start event: 46228b8bc22044aaa9387f7d015dc687
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: QUALCOMM build                   : ee99c0bfce, Icd6d974f18
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Build Date                       : 11/11/22
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.36.08.11
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Local Branch                     : 
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Remote Branch                    : 
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Remote Branch                    : 
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Reconstruct Branch               : 
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Build Config                     : S P 12.1.1 AArch64
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-03 09:39:28.121 22313 23757 I AdrenoGLES-0: Driver Version                   : 0615.52
07-03 09:39:28.126 22313 23757 I AdrenoGLES-0: PFP: 0x01730155, ME: 0x00000000
07-03 09:39:28.141 22313 23757 I OpenGLRenderer: setGrContext nullptr-->validptr
07-03 09:39:28.163 22313 23757 W Parcel  : Expecting binder but got null!
07-03 09:39:28.167 22313 22313 D SessionLifecycleClient: Session update received: 46228b8bc22044aaa9387f7d015dc687
07-03 09:39:28.168 22313 22340 D SessionLifecycleClient: Notified CRASHLYTICS of new session 46228b8bc22044aaa9387f7d015dc687
07-03 09:39:28.255 22313 22313 W View    : requestLayout() improperly called by eu.kanade.tachiyomi.ui.library.LibraryFastScroll{92a8b7c V.E...... ......ID 0,230-1080,2170 #7f0b015a app:id/fast_scroller} during layout: running second layout pass
07-03 09:39:29.761 22313 22313 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:39:29.761 22313 22313 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:39:29.761 22313 22313 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-03 09:39:29.761 22313 22313 D VRI[MainActivity]:   bhv=DEFAULT
07-03 09:39:29.761 22313 22313 D VRI[MainActivity]:   fitSides=} by setLayoutParams
07-03 09:39:29.954 22313 23832 D TrafficStats: tagSocket(143) with statsTag=0xffffffff, statsUid=-1
07-03 09:39:29.954 22313 23828 D TrafficStats: tagSocket(142) with statsTag=0xffffffff, statsUid=-1
07-03 09:39:29.954 22313 23830 D TrafficStats: tagSocket(157) with statsTag=0xffffffff, statsUid=-1
07-03 09:39:29.954 22313 23831 D TrafficStats: tagSocket(158) with statsTag=0xffffffff, statsUid=-1
07-03 09:39:29.954 22313 23827 D TrafficStats: tagSocket(190) with statsTag=0xffffffff, statsUid=-1
07-03 09:39:31.932 22313 22325 I .nekomanga.neko: Background concurrent mark compact GC freed 369456(16MB) AllocSpace objects, 250(16MB) LOS objects, 75% free, 17MB/68MB, paused 915us,3.107ms total 120.320ms
07-03 09:39:31.943 22313 22327 W System  : A resource failed to call close. 
07-03 09:39:34.249 22313 22356 D SessionLifecycleClient: Sending lifecycle 2 to service
07-03 09:39:34.249 22313 22374 D SessionLifecycleService: Activity backgrounding at 252154183
07-03 09:39:34.252 22313 23787 E SQLiteLog: (284) automatic index on mangas(_id)
07-03 09:39:34.616 22313 23757 D Surface : Surface::disconnect
07-03 09:39:34.616 22313 23757 D BufferQueueProducer: [VRI[MainActivity]#0(BLAST Consumer)0](id:572900000000,api:1,p:22313,c:22313) disconnect: api 1
07-03 09:39:36.268 22313 23771 I FA      : Application backgrounded at: timestamp_millis: 1720013974265
07-03 09:40:03.671 22313 22355 I TRuntime.CctTransportBackend: Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
07-03 09:40:03.844 22313 22355 I TRuntime.CctTransportBackend: Status Code: 200
07-03 09:40:14.689 22313 22340 D SessionLifecycleClient: Sending lifecycle 1 to service
07-03 09:40:14.691 22313 22313 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:40:14.691 22313 22313 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:40:14.691 22313 22313 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
07-03 09:40:14.691 22313 22313 D VRI[MainActivity]:   bhv=DEFAULT
07-03 09:40:14.691 22313 22313 D VRI[MainActivity]:   fitSides=} by setLayoutParams
07-03 09:40:14.691 22313 22374 D SessionLifecycleService: Activity foregrounding at 252194624.
07-03 09:40:15.863 22313 22313 D ViewRootImpl: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.863 22313 22313 D ViewRootImpl:   fl=WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.863 22313 22313 D ViewRootImpl:   bhv=DEFAULT
07-03 09:40:15.863 22313 22313 D ViewRootImpl:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setView
07-03 09:40:15.879 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.879 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.879 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.879 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.880 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.880 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.880 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.880 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.881 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.881 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.881 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.881 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.883 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.884 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.884 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.884 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.884 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.953 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(wrapxwrap) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.953 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.953 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.953 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.964 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.964 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.964 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.964 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.970 22313 23757 W Parcel  : Expecting binder but got null!
07-03 09:40:15.976 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.976 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.976 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.976 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:15.982 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:15.982 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:15.982 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:15.982 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:17.315 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:17.315 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:17.315 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:17.315 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:17.367 22313 22313 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:40:17.367 22313 22313 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:40:17.367 22313 22313 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-03 09:40:17.367 22313 22313 D VRI[MainActivity]:   bhv=DEFAULT
07-03 09:40:17.367 22313 22313 D VRI[MainActivity]:   fitSides=} by setLayoutParams
07-03 09:40:17.372 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:17.372 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:17.372 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:17.372 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:17.373 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:17.376 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:17.376 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:17.376 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:17.376 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:17.381 22313 22313 D VRI[Pop-Up Window]: update {(0,0)(1080x2250) gr=TOP START CENTER ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT
07-03 09:40:17.381 22313 22313 D VRI[Pop-Up Window]:   fl=NOT_FOCUSABLE WATCH_OUTSIDE_TOUCH HARDWARE_ACCELERATED
07-03 09:40:17.381 22313 22313 D VRI[Pop-Up Window]:   bhv=DEFAULT
07-03 09:40:17.381 22313 22313 D VRI[Pop-Up Window]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
07-03 09:40:17.706 22313 23757 D Surface : Surface::disconnect
07-03 09:40:17.706 22313 23757 D BufferQueueProducer: [VRI[Pop-Up Window]#2(BLAST Consumer)2](id:572900000002,api:1,p:22313,c:22313) disconnect: api 1
07-03 09:40:17.708 22313 23757 D OpenGLRenderer: endAllActiveAnimators on 0xb40000700932a620 (UnprojectedRipple) with handle 0xb400006f18ee7340
07-03 09:40:24.588 22313 22313 D VRI[MainActivity]: update {(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030300
07-03 09:40:24.588 22313 22313 D VRI[MainActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-03 09:40:24.588 22313 22313 D VRI[MainActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-03 09:40:24.588 22313 22313 D VRI[MainActivity]:   bhv=DEFAULT
07-03 09:40:24.588 22313 22313 D VRI[MainActivity]:   fitSides=} by setLayoutParams

### Neko version

App version: 2.16.9 (standard, b6d958781, 10, 2024-06-28T00:51:12.841592104)

### Android version

 13 (SDK 33)

### Device

motorola edge plus (2022)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by danuharyp** [comment]
Encountering this bug too

**Comment by nonproto** [comment]
#1891
