### ISSUE TITLE
Crash after changing Komga password

### ISSUE THREAD

**Issue by Norsze** [nekomangaorg/Neko#1878]
### Steps to reproduce

1. Login to Komga
2. Merge a manga with Komga (don't know if this is necessary)
3. Change password in the Komga server without changing first in the app.
4. Navigate to merge settings.
5. Crash.

### Expected behavior

Able to make changes in merge settings

### Actual behavior

Crash as soon as merge settings is opened.

### Crash logs

[neko_crash_logs (1).txt](https://github.com/user-attachments/files/16125827/neko_crash_logs.1.txt)

### Neko version

App version: 2.16.9 (standard, b6d958781, 10, 2024-06-28T00:51:12.841592104)

### Android version

Android version: 14 (SDK 34) Android build ID: UP1A.231005.007.S906BXXSAEXEC

### Device

Device brand: samsung Device manufacturer: samsung Device name: g0s Device model: SM-S906B Device product name: g0sxeea

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Are you unable to click the logout button?  I tried to emulate this but am not getting an error

**Comment by nonproto** [comment]
hmm i dont know why it would as it doesnt try to login or use login at all during that screen
