### ISSUE TITLE
Clicking on search button crashes the application 

### ISSUE THREAD

**Issue by SHELIDRAN** [nekomangaorg/Neko#1890]
### Steps to reproduce

> Go to browse page
> click on search

### Expected behavior

Take you to search

### Actual behavior

Crash

### Crash logs

[neko_crash_log-202407250020.txt](https://github.com/user-attachments/files/16366447/neko_crash_log-202407250020.txt)

### Neko version

v2.16.10

### Android version

Android 15 beta 4

### Device

Google pixel 7 pro

### Other details

Faced the issue in previous version of application too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
See the other closed issues on this
