### ISSUE TITLE
Keep getting exception throw when try to Open search manga box/search preset

### ISSUE THREAD

**Issue by TanagiMS** [nekomangaorg/Neko#1891]
### Steps to reproduce

1.Go to Browse
2.Tap Search

### Expected behavior

I suppose to open my search box normally 

### Actual behavior

The app throw exception 

### Crash logs

[neko_crash_log-202407260151.txt](https://github.com/user-attachments/files/16382597/neko_crash_log-202407260151.txt)

### Neko version

2.16.10 and before

### Android version

Android 13

### Device

ZTE Nubia Neo 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by freigus** [comment]
I have a similar error when opening Browse tab. Version 2.16.10
I can create a separate issue if required.
## Steps to reproduce
1. Open Neko
2. Try to open Browse tab

Error: `kotlinx.serialization.SerializationException: eu.kanade.tachiyomi.source.model.MangaTag does not contain element with name 'ECCHI' at path $.tags[16].tag`
Logs: [neko_crash_log-202407260511.txt](https://github.com/user-attachments/files/16382744/neko_crash_log-202407260511.txt)

**Comment by nonproto** [comment]
Search the closed issues
