### ISSUE TITLE
Neko crashes when opening Search on Browse page

### ISSUE THREAD

**Issue by thagiat** [nekomangaorg/Neko#1895]
### Steps to reproduce

1. Click Browse sub-menu
2. Click Search
3. Crash menu appears(dump crash log or restart application)

### Expected behavior

Open the search menu, to look for new mangas

### Actual behavior

The app crashes with this solicitation

### Crash logs

[neko_crash_log-202407311411.txt](https://github.com/user-attachments/files/16445191/neko_crash_log-202407311411.txt)

### Neko version

2.16.10

### Android version

Android 14

### Device

Samsung Galaxy S24 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Search the closed tickets
