### ISSUE TITLE
Neko will crash whenever i use search bar 

### ISSUE THREAD

**Issue by Flylikeicarus** [nekomangaorg/Neko#1897]
### Steps to reproduce

Firstly when I open the app I go to the browse section, then as soon as I click on the search button to pull up the search bar it just immediately crashes

### Expected behavior

Normally the response is that the search bar opens up and allows me to open it and use it to filter through manga and search normally

### Actual behavior

Instead of the search bar opening it simply crashes and asks to restart application 

### Crash logs

[neko_crash_log-202408090828.txt](https://github.com/user-attachments/files/16563756/neko_crash_log-202408090828.txt)

### Neko version

2.16.10

### Android version

14

### Device

Samsung galaxy a14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Search the closed issues
