### ISSUE TITLE
Backup Settings option

### ISSUE THREAD

**Issue by Ashkar666** [nekomangaorg/Neko#1899]
### Describe your suggested feature

Please add a "Backup Mangadex Settings" function for in case a reinstall is needed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
At this time there is no plans to add this
