### ISSUE TITLE
Unable to make a manual backup

### ISSUE THREAD

**Issue by ArkNonCreator** [nekomangaorg/Neko#1918]
### Steps to reproduce

Steps.
1: Open "Data and Storage" menu in the settings.
2: Select "Create backup".
3: Leave all check boxes enabled.
4: Select folder for the creation of backup file.

### Expected behavior

Successful creation of the backup file.

### Actual behavior

![Screenshot_20240818-131900_Neko](https://github.com/user-attachments/assets/710ceb66-f0a0-40a8-b540-ea20d33b2147)

### Crash logs

[neko_crash_log-202408181318.txt](https://github.com/user-attachments/files/16650111/neko_crash_log-202408181318.txt)

### Neko version

2.17.0

### Android version

Android 13

### Device

Samsung Galaxy A10 (A105M)

### Other details

The crash log was made after a full device reboot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by traddon** [comment]
Seems to also affect automatic backups too. My last auto backup is from August 14, despite having auto backups enabled.

**Comment by nonproto** [comment]
Resolved in 2.17.1
