### ISSUE TITLE
Crash on library manga page refresh

### ISSUE THREAD

**Issue by solntcev** [nekomangaorg/Neko#1921]
### Steps to reproduce

1. Open manga added to library
2. Pull page to refresh

### Expected behavior

Manga pages refreshed: pulled new chapters, comment counters.

### Actual behavior

App show loadaing indicator an then crashes

### Crash logs

[neko_crash_log-202409210031.txt](https://github.com/user-attachments/files/17089427/neko_crash_log-202409210031.txt)
[neko_crash_log-202409210052.txt](https://github.com/user-attachments/files/17089428/neko_crash_log-202409210052.txt)

### Neko version

2.17.1

### Android version

Android 8

### Device

Huawei MediaPad T5

### Other details

I am logged-in with MangaDex, did not check how it behaves while logged out.

Crash can avoided if I open any manga from "Browse" section, then refreshing manga in Library works fine.

Looks like issue is with WebView that provided with Chrome, but not sure what is it. And why it is not triggering on pages in Browse.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Do you have webview disabled on your device if not is it up to date?
