### ISSUE TITLE
Pls add mangahasu and mangago as a source

### ISSUE THREAD

**Issue by Aruraka** [nekomangaorg/Neko#1926]
### Describe your suggested feature

1) https://mangahasu.me/directory.html
2)https://www.mangago.me/home/accounts/register/

### Other details

I have added these two links pls add them:))

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by nonproto** [comment]
No new sources are being added just replacing mangalife with it's successor
