### ISSUE TITLE
Crash Upon Search in Browse Section

### ISSUE THREAD

**Issue by babyblasphemy** [nekomangaorg/Neko#1980]
### Steps to reproduce

Navigate to Browse Section. Select Search. Crash.

### Expected behavior

The search menu should open.

### Actual behavior

Crash.

### Crash logs

[neko_crash_log-202411270053.txt](https://github.com/user-attachments/files/17929792/neko_crash_log-202411270053.txt)

### Neko version

2.18.1

### Android version

Android 15

### Device

Google Pixel 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
You need to go to settings -> mangadex and clear your search filters
