### ISSUE TITLE
search function instantly crashes app

### ISSUE THREAD

**Issue by azzy96** [nekomangaorg/Neko#1984]
### Steps to reproduce

1. Open or reenter Neko
2. Select Browse
3. Select Search
4. Boom, instant crash!

### Expected behavior

Search parameters should slide up from bottom and the app to not crash

### Actual behavior

Instant crash upon selecting search function

### Crash logs

[neko_crash_log-202411300624.txt](https://github.com/user-attachments/files/17962598/neko_crash_log-202411300624.txt)

### Neko version

App version: 2.18.2 (standard, b922d2838, 16, 2024-11-27T01:16:06.20432505)

### Android version

Android version: 14 (SDK 34)

### Device

Google Pixel 6a

### Other details

Android build ID: AP2A.240905.003.F1
Device brand: google
Device manufacturer: Google
Device name: bluejay
Device model: Pixel 6a
Device product name: bluejay

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Clear search filters in mangadex settings
