### ISSUE TITLE
Opening search crashes with unsupported language LINTHUANIAN

### ISSUE THREAD

**Issue by Sanae6** [nekomangaorg/Neko#1985]
### Steps to reproduce

1. Open browse tab
2. Tap search
3. Crash (yeah that's kinda it)

### Expected behavior

No crash

### Actual behavior

MdLang doesn't have [LINTHUANIAN](https://github.com/nekomangaorg/Neko/blob/main/app%2Fsrc%2Fmain%2Fjava%2Feu%2Fkanade%2Ftachiyomi%2Fsource%2Fonline%2Futils%2FMdLang.kt#L43) so it crashes the moment I try to start search. 

### Crash logs

[neko_crash_log-202412011012.txt](https://github.com/user-attachments/files/17969513/neko_crash_log-202412011012.txt)

### Neko version

2.18.2

### Android version

Android 13

### Device

Samsung Galaxy S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Clear search filters in mangadex settings
