### ISSUE TITLE
MAL manga list not syncing

### ISSUE THREAD

**Issue by Bumpf** [nekomangaorg/Neko#1987]
### Steps to reproduce

1. Connect Mangadex account to Neko and add library
2. Connect MAL account (I just created a new account, I'm attempting to migrate my library)
3. Check your Manga List on MAL

### Expected behavior

My library of manga should appear in MAL's Manga List 

### Actual behavior

Instead, it is empty.

### Neko version

2.18.2

### Android version

Android 11

### Device

Moto g Power (2021)

### Other details

I may be misinterpreting what "tracking" is supposed to do. Does it actually only take *from* MAL instead of sending to it? If so, please let me know how I can send my MangaDex library to my MAL account (with sync, preferably). And yes, I have tried MAL-Sync but am unable to get it to work (I really don't know GitHub)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
The app doesn't auto add your library to a tracker

**Comment by Bumpf** [comment]
FUCK
thanks for the response though :)
