### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by Sans000ye** [nekomangaorg/Neko#1989]
### Steps to reproduce

Press the search button on "browse" tabs

### Expected behavior

The search tab is open and full access to the search function

### Actual behavior

The app pulls up the search tab

### Crash logs

![Screenshot_20241203_003026](https://github.com/user-attachments/assets/dfd4b14c-c1c1-46ca-8104-be546ef5d054)

### Neko version

2.18.2

### Android version

Android 14

### Device

Samsung galaxy s23 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Delete search filters in mangadex settings
