### ISSUE TITLE
Error when using search

### ISSUE THREAD

**Issue by Glonthein** [nekomangaorg/Neko#1994]
### Steps to reproduce

-Open Neko
-Go to "Browse" category
-Tap "Search" button

### Expected behavior

Search menu should open filter and preset options

### Actual behavior

An error log immediately appears, the issue remains after relaunching the app or even the phone. 

### Crash logs

[neko_crash_log-202412061917.txt](https://github.com/user-attachments/files/18042157/neko_crash_log-202412061917.txt)

### Neko version

2.18.2

### Android version

Android 10

### Device

Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by wesh92** [comment]
I had this issue as well and had to clear my saved filters. If you want to do that you'd go to Settings -> MangaDex Settings -> Delete saved filters. Hopefully someone else will have a less destructive method though.

**Comment by nonproto** [comment]
the above is the solution
