### ISSUE TITLE
App crashes when using the search button

### ISSUE THREAD

**Issue by Lanzdaninja** [nekomangaorg/Neko#1995]
### Steps to reproduce

Step 1: Go to Browse Tab
Step 2: Press search

### Expected behavior

Show the search menu

### Actual behavior

It crashes

### Crash logs

[neko_crash_log-202412081855.txt](https://github.com/user-attachments/files/18051733/neko_crash_log-202412081855.txt)

### Neko version

2.18.2

### Android version

Android 10

### Device

Samsung Galaxy

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by nonproto** [comment]
Clear search filters in mangadex settings
