### ISSUE TITLE
Version update download does nothing

### ISSUE THREAD

**Issue by stgnet** [nekomangaorg/Neko#415]
### Device information
* Tachiyomi version: neko 2.1.5.5
* Android phone & version: pvg100 8.1

## Steps to reproduce
1. Neko detects new version, offers download button
2. Tap download, but nothing happens. No error, no download.

### Expected behavior
Download of new version followed by prompt to install

### Actual behavior
Nothing

### Other details
Has been going on for months, happened on moto z3 play also.

**Comment by CarlosEsco** [comment]
Can you download it directly?

https://github.com/CarlosEsco/Neko/releases/tag/2.1.5.6.1

I am not doing anything special that would prevent a download from occurring and nobody in discord has complained about this before

**Comment by stgnet** [comment]
Yes, I've been downloading it directly about once a month (not every release).  The download button has done nothing for me consistently over the last many months, and on two different android phones.  I know about a year ago or so it was working, but more recently I've not been able to update automatically, only manually by downloading and installing the apk outside of neko itself.

**Comment by CarlosEsco** [comment]
I'm wondering if the phone is doing something no standard in its OS.  
https://github.com/CarlosEsco/Neko/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/notification/NotificationHandler.kt#L50

I am not finding any other way to do an apk install intent besides setting this application/vnd.android.package-archive

**Comment by stgnet** [comment]
Is there any way to get feedback on the progress of the upgrade request?  Possibly the issue in my case is that the app doesn't have sufficient permission.  The silent failure is the real bug here.

**Comment by CarlosEsco** [comment]
If you can export the error log in advanced settings.  After a failed download attempt it might show something.

**Comment by CarlosEsco** [comment]
Also i sent the wrong code block
this is the service that gets started after the download button clicked.

https://github.com/CarlosEsco/Neko/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdaterService.kt

**Comment by nonproto** [comment]
Closing for being stale
