### ISSUE TITLE
Sync Mangadex v5 "My Lists" to neko categories

### ISSUE THREAD

**Issue by Nats1113** [nekomangaorg/Neko#609]
Essentially, I want my categories to be lists and my lists to be categories.

**Comment by CarlosEsco** [comment]
if this gets added in the future it would probably be a one time sync, and not a real time sync

**Comment by nonproto** [comment]
So with the new custom lists that will go to production at some point. You will be able to group the library by your custom lists whatever they are named. So I won't be adding this specific syncing
